# Copyright (c) 2026, Frappe Technologies Pvt. Ltd. and Contributors
# See license.txt

"""
Coverage tests for the Donation Campaign DocType controller.

Targets verenigingen/verenigingen/doctype/donation_campaign/donation_campaign.py:
  - validate_dates / validate_goals throws
  - set_accounting_dimension_value (auto-gen, uniqueness suffix, digit prefix,
    minimum-length fallback)
  - update_progress (totals / unique donors / averages / percentages)
  - get_recent_donations / get_top_donors (show_donor_list gate + aggregation)
  - get_campaign_url (public+website vs None)
  - create_project (throws on existing link / duplicate name / no start_date;
    real Project creation + back-link)
  - get_project_summary (None / real summary)
  - get_accounting_entries
  - get_active_campaigns staticmethod
  - module-level update_campaign_progress (SQL aggregation + db_update)

All real-DB integration tests. No business logic is mocked. frappe.sendmail is
patched only around Donation inserts (they enqueue a confirmation email).
"""

from unittest.mock import patch

import frappe

from verenigingen.tests.fixtures.enhanced_test_factory import EnhancedTestCase


class TestDonationCampaignCoverage(EnhancedTestCase):
    def setUp(self):
        super().setUp()
        companies = frappe.get_all("Company", limit=1)
        self.test_company = companies[0].name if companies else "_Test Company"

    # ------------------------------------------------------------------
    # helpers
    # ------------------------------------------------------------------
    def _make_campaign(self, **overrides):
        campaign = frappe.new_doc("Donation Campaign")
        campaign.campaign_name = overrides.pop(
            "campaign_name", f"Camp {self.test_run_id} {frappe.generate_hash()[:6]}"
        )
        campaign.campaign_type = overrides.pop("campaign_type", "Project Funding")
        campaign.status = overrides.pop("status", "Active")
        campaign.start_date = overrides.pop("start_date", frappe.utils.today())
        for key, value in overrides.items():
            setattr(campaign, key, value)
        campaign.insert()
        return campaign

    def _make_donor(self):
        donor = frappe.new_doc("Donor")
        donor.donor_name = f"CC Donor {self.test_run_id} {frappe.generate_hash()[:6]}"
        donor.donor_type = "Individual"
        donor.donor_email = f"cc-{self.test_run_id}-{frappe.generate_hash()[:6]}@example.com"
        donor.insert()
        return donor

    def _ensure_mode_of_payment(self, name="Test Payment"):
        if not frappe.db.exists("Mode of Payment", name):
            mode = frappe.new_doc("Mode of Payment")
            mode.mode_of_payment = name
            mode.insert()
        return name

    def _make_paid_donation(self, campaign_name, donor, amount, anonymous=0):
        donation = frappe.new_doc("Donation")
        donation.donor = donor.name
        donation.amount = amount
        donation.donation_date = frappe.utils.today()
        donation.company = self.test_company
        donation.mode_of_payment = self._ensure_mode_of_payment()
        donation.campaign = campaign_name
        donation.paid = 1
        donation.anonymous = anonymous
        with patch("frappe.sendmail"):
            donation.insert()
        return donation

    # ------------------------------------------------------------------
    # validate_dates / validate_goals
    # ------------------------------------------------------------------
    def test_end_before_start_throws(self):
        from frappe.utils import add_days

        with self.assertRaises(frappe.ValidationError):
            self._make_campaign(
                start_date=frappe.utils.today(),
                end_date=add_days(frappe.utils.today(), -5),
            )

    def test_negative_monetary_goal_throws(self):
        with self.assertRaises(frappe.ValidationError):
            self._make_campaign(monetary_goal=-100)

    def test_negative_donor_goal_throws(self):
        with self.assertRaises(frappe.ValidationError):
            self._make_campaign(donor_goal=-5)

    # ------------------------------------------------------------------
    # set_accounting_dimension_value()
    # ------------------------------------------------------------------
    def test_dimension_value_autogenerated_from_name(self):
        """The dimension value is derived from the uppercased, underscored name."""
        campaign = self._make_campaign(campaign_name="Save The Whales 2026")
        self.assertTrue(campaign.accounting_dimension_value.startswith("SAVE_THE_WHALES_2026"))

    def test_dimension_value_uniqueness_suffix(self):
        """A second campaign whose name yields the SAME sanitized base dimension
        gets a _N suffix. The two campaign_names differ only by a trailing '!'
        (stripped during sanitization) so primary keys stay distinct while the
        derived dimension base collides."""
        tag = frappe.generate_hash()[:6].upper()
        c1 = self._make_campaign(campaign_name=f"Dim Base {tag}")
        base = c1.accounting_dimension_value
        self.assertEqual(base, f"DIM_BASE_{tag}")
        c2 = self._make_campaign(campaign_name=f"Dim Base {tag}!")
        # Same sanitized base -> uniqueness loop appends a suffix.
        self.assertNotEqual(c2.accounting_dimension_value, base)
        self.assertTrue(c2.accounting_dimension_value.startswith(base[: 50 - 2]))

    def test_dimension_value_digit_prefix_gets_camp_prefix(self):
        """A name starting with a digit yields a dimension value prefixed CAMP_."""
        campaign = self._make_campaign(campaign_name="2026 Year End Drive")
        self.assertTrue(campaign.accounting_dimension_value.startswith("CAMP_"))

    def test_dimension_value_minimum_length_fallback(self):
        """A name that sanitizes to fewer than 3 chars falls back to CAMP_<hash>."""
        # "!!" sanitizes to empty -> fallback CAMP_<hash8>
        campaign = self._make_campaign(campaign_name="!!")
        self.assertTrue(campaign.accounting_dimension_value.startswith("CAMP_"))
        self.assertGreaterEqual(len(campaign.accounting_dimension_value), 3)

    def test_dimension_value_preserved_if_provided(self):
        """An explicitly provided dimension value is not overwritten."""
        explicit = f"EXPLICIT_{frappe.generate_hash()[:6].upper()}"
        campaign = self._make_campaign(accounting_dimension_value=explicit)
        self.assertEqual(campaign.accounting_dimension_value, explicit)

    # ------------------------------------------------------------------
    # update_progress()
    # ------------------------------------------------------------------
    def test_update_progress_computes_totals_and_percentages(self):
        """update_progress aggregates paid donations into totals, unique donors,
        average, and goal percentages."""
        campaign = self._make_campaign(monetary_goal=1000, donor_goal=4)
        d1 = self._make_donor()
        d2 = self._make_donor()
        self._make_paid_donation(campaign.name, d1, 100)
        self._make_paid_donation(campaign.name, d1, 300)  # same donor again
        self._make_paid_donation(campaign.name, d2, 100)

        campaign.save()  # validate() -> update_progress()
        campaign.reload()

        self.assertEqual(campaign.total_donations, 3)
        self.assertEqual(campaign.total_raised, 500)
        self.assertEqual(campaign.total_donors, 2)  # unique
        self.assertEqual(campaign.average_donation_amount, round(500 / 3, 2))
        self.assertEqual(campaign.monetary_progress, 50.0)  # 500/1000
        self.assertEqual(campaign.donor_progress, 50.0)  # 2/4

    def test_update_progress_zero_donations(self):
        """With no donations all computed progress fields are zero."""
        campaign = self._make_campaign(monetary_goal=1000)
        campaign.save()
        campaign.reload()
        self.assertEqual(campaign.total_donations, 0)
        self.assertEqual(campaign.total_raised, 0)
        self.assertEqual(campaign.average_donation_amount, 0)
        self.assertEqual(campaign.monetary_progress, 0)

    # ------------------------------------------------------------------
    # get_recent_donations() / get_top_donors()
    # ------------------------------------------------------------------
    def test_get_top_donors_empty_when_list_hidden(self):
        """get_top_donors returns [] when show_donor_list is off."""
        campaign = self._make_campaign(show_donor_list=0)
        self.assertEqual(campaign.get_top_donors(), [])

    def test_get_recent_donations_returns_list(self):
        """get_recent_donations returns a list (Donation is not submittable, so
        its docstatus=1 filter yields no rows — documents that behavior)."""
        campaign = self._make_campaign()
        donor = self._make_donor()
        self._make_paid_donation(campaign.name, donor, 100)
        result = campaign.get_recent_donations()
        # Donation has no docstatus workflow (always 0); the docstatus=1 filter
        # means this list is empty in practice.
        self.assertIsInstance(result, list)

    def test_get_top_donors_returns_list_when_shown(self):
        """get_top_donors returns a list when show_donor_list is on (docstatus=1
        filter means empty for non-submittable Donation)."""
        campaign = self._make_campaign(show_donor_list=1)
        donor = self._make_donor()
        self._make_paid_donation(campaign.name, donor, 100)
        result = campaign.get_top_donors()
        self.assertIsInstance(result, list)

    # ------------------------------------------------------------------
    # get_campaign_url()
    # ------------------------------------------------------------------
    def test_campaign_url_public_and_on_website(self):
        campaign = self._make_campaign(is_public=1, show_on_website=1)
        self.assertEqual(campaign.get_campaign_url(), f"/campaign/{campaign.name}")

    def test_campaign_url_none_when_not_public(self):
        campaign = self._make_campaign(is_public=0, show_on_website=1)
        self.assertIsNone(campaign.get_campaign_url())

    def test_campaign_url_none_when_not_on_website(self):
        campaign = self._make_campaign(is_public=1, show_on_website=0)
        self.assertIsNone(campaign.get_campaign_url())

    # ------------------------------------------------------------------
    # create_project()
    # ------------------------------------------------------------------
    def test_create_project_creates_and_links(self):
        campaign = self._make_campaign()
        project_name = f"Proj {self.test_run_id} {frappe.generate_hash()[:6]}"
        with self.assertNoErrorLog():
            project = campaign.create_project(project_name=project_name)
        self.assertTrue(frappe.db.exists("Project", project.name))
        campaign.reload()
        self.assertEqual(campaign.project, project.name)

    def test_create_project_throws_when_already_linked(self):
        campaign = self._make_campaign()
        campaign.create_project(project_name=f"Proj A {self.test_run_id} {frappe.generate_hash()[:6]}")
        campaign.reload()
        with self.assertRaises(frappe.ValidationError):
            campaign.create_project(project_name=f"Proj B {self.test_run_id} {frappe.generate_hash()[:6]}")

    def test_create_project_throws_on_duplicate_name(self):
        existing_name = f"Dup Proj {self.test_run_id} {frappe.generate_hash()[:6]}"
        proj = frappe.get_doc(
            {
                "doctype": "Project",
                "project_name": existing_name,
                "company": self.test_company,
                "status": "Open",
            }
        )
        proj.insert()
        campaign = self._make_campaign()
        with self.assertRaises(frappe.ValidationError):
            campaign.create_project(project_name=existing_name)

    def test_create_project_throws_without_start_date(self):
        # Build a campaign then strip its start_date in DB to hit the guard.
        campaign = self._make_campaign()
        frappe.db.set_value("Donation Campaign", campaign.name, "start_date", None)
        campaign.reload()
        with self.assertRaises(frappe.ValidationError):
            campaign.create_project(project_name=f"NoStart {self.test_run_id} {frappe.generate_hash()[:6]}")

    # ------------------------------------------------------------------
    # get_project_summary()
    # ------------------------------------------------------------------
    def test_get_project_summary_none_without_project(self):
        campaign = self._make_campaign()
        self.assertIsNone(campaign.get_project_summary())

    def test_get_project_summary_returns_summary_with_project(self):
        campaign = self._make_campaign()
        campaign.create_project(project_name=f"Sum Proj {self.test_run_id} {frappe.generate_hash()[:6]}")
        campaign.reload()
        summary = campaign.get_project_summary()
        self.assertIsNotNone(summary)
        self.assertIn("project", summary)
        self.assertIn("tasks", summary)
        self.assertEqual(summary["total_expenses"], 0)
        self.assertEqual(summary["task_completion"], 0)

    # ------------------------------------------------------------------
    # get_accounting_entries()
    # ------------------------------------------------------------------
    def test_get_accounting_entries_includes_paid_donations(self):
        """get_accounting_entries must not crash when filtering by the campaign
        accounting dimension.

        Regression guard for the has_field() fix: validate() always sets
        accounting_dimension_value, so the method would build a
        filters["custom_campaign_dimension"] entry and frappe.get_all would raise
        on the unknown column on any site WITHOUT that custom field (e.g. fresh CI
        sites). The fix guards the filter with GL Entry.has_field(...). We assert
        the precondition (dimension value present) so the guarded branch is reached,
        then that the call returns the expected shape without raising.

        Note: Donation is not submittable, so the method's docstatus=1 donation
        filter returns nothing -> total_income stays 0. This documents (does not
        endorse) the controller's current behavior; see the flagged follow-up.
        """
        campaign = self._make_campaign()
        donor = self._make_donor()
        self._make_paid_donation(campaign.name, donor, 250)
        # Precondition: the dimension value is set, so the has_field-guarded branch
        # is actually exercised (otherwise the fix path is never reached).
        self.assertTrue(campaign.accounting_dimension_value)
        with self.assertNoErrorLog():
            entries = campaign.get_accounting_entries()
        self.assertIsInstance(entries["gl_entries"], list)
        self.assertIsInstance(entries["donations"], list)
        # docstatus=1 filter on a non-submittable doctype -> no donation rows.
        self.assertEqual(entries["donations"], [])
        self.assertEqual(entries["total_income"], 0)

    # ------------------------------------------------------------------
    # get_active_campaigns() staticmethod
    # ------------------------------------------------------------------
    def test_get_active_campaigns_includes_public_active(self):
        from verenigingen.verenigingen.doctype.donation_campaign.donation_campaign import DonationCampaign

        campaign = self._make_campaign(status="Active", is_public=1, show_on_website=1)
        names = [c.name for c in DonationCampaign.get_active_campaigns()]
        self.assertIn(campaign.name, names)

    def test_get_active_campaigns_excludes_non_public(self):
        from verenigingen.verenigingen.doctype.donation_campaign.donation_campaign import DonationCampaign

        campaign = self._make_campaign(status="Active", is_public=0, show_on_website=0)
        names = [c.name for c in DonationCampaign.get_active_campaigns()]
        self.assertNotIn(campaign.name, names)

    # ------------------------------------------------------------------
    # module-level update_campaign_progress()
    # ------------------------------------------------------------------
    def test_module_update_campaign_progress_aggregates(self):
        from verenigingen.verenigingen.doctype.donation_campaign.donation_campaign import (
            update_campaign_progress,
        )

        campaign = self._make_campaign(monetary_goal=500, donor_goal=2)
        d1 = self._make_donor()
        d2 = self._make_donor()
        self._make_paid_donation(campaign.name, d1, 100)
        self._make_paid_donation(campaign.name, d2, 150, anonymous=0)

        with self.assertNoErrorLog():
            update_campaign_progress(campaign.name)

        campaign.reload()
        self.assertEqual(campaign.total_donations, 2)
        self.assertEqual(campaign.total_raised, 250)
        self.assertEqual(campaign.total_donors, 2)
        self.assertEqual(campaign.monetary_progress, 50.0)  # 250/500
        self.assertEqual(campaign.donor_progress, 100.0)  # 2/2

    def test_module_update_campaign_progress_excludes_anonymous_from_donor_count(self):
        """Anonymous paid donations count toward totals/raised but NOT unique donors."""
        from verenigingen.verenigingen.doctype.donation_campaign.donation_campaign import (
            update_campaign_progress,
        )

        campaign = self._make_campaign()
        d1 = self._make_donor()
        d2 = self._make_donor()
        self._make_paid_donation(campaign.name, d1, 100, anonymous=0)
        self._make_paid_donation(campaign.name, d2, 100, anonymous=1)

        update_campaign_progress(campaign.name)
        campaign.reload()
        self.assertEqual(campaign.total_donations, 2)
        self.assertEqual(campaign.total_raised, 200)
        # Anonymous donor excluded from DISTINCT donor count -> only 1.
        self.assertEqual(campaign.total_donors, 1)
