# Copyright (c) 2025, Frappe Technologies and contributors
# For license information, please see license.txt

"""
Integration tests for ChapterPermissionService - Real database testing

Tests verify permission logic with actual database operations:
- Admin/staff/board member/regular member access patterns
- Row-level security enforcement
- Permission query generation
- Board membership verification

Uses Enhanced Test Factory for realistic test data.
No database mocking - all operations use real Frappe database.

Note: This test creates persistent test data in setUpClass with explicit commit
to work around Frappe's test transaction isolation. Data is cleaned up in tearDownClass.
"""

import unittest
from unittest.mock import patch
import frappe
from frappe.utils import today
from verenigingen.tests.fixtures.enhanced_test_factory import EnhancedTestCase
from verenigingen.services.chapter.chapter_permission_service import (
    ChapterPermissionService,
    get_chapter_permission_service,
)


class TestChapterPermissionServiceIntegration(EnhancedTestCase):
    """Integration test suite for ChapterPermissionService with real database"""

    # Class-level tracking for cleanup
    _created_users = []
    _created_chapters = []
    _created_members = []
    _created_volunteers = []

    @classmethod
    def setUpClass(cls):
        """Set up test data once for all tests (performance optimization)"""
        super().setUpClass()

        # Reset tracking lists
        cls._created_users = []
        cls._created_chapters = []
        cls._created_members = []
        cls._created_volunteers = []

        # ISOLATION: derive UNIQUE test emails per class run. The permission
        # branches keyed off these users (admin/board/regular) are extremely
        # sensitive to leaked state — a sibling test in ANOTHER file that
        # creates/modifies/deletes a User or Member/Volunteer with the SAME
        # email, or grafts extra roles/board-memberships onto that user, would
        # corrupt this class's expectations across CI shard execution order.
        # Per-run unique emails make any cross-file collision impossible.
        run_id = frappe.generate_hash(length=8)
        cls.admin_email = f"admin-{run_id}@verenigingen.test"
        cls.board_email = f"board-{run_id}@verenigingen.test"
        cls.regular_email = f"regular-{run_id}@verenigingen.test"

        # Create a temporary instance to use factory methods
        cls._test_instance = cls()
        cls._test_instance.setUp()  # Initialize factory

        # Create test chapters - chapter names are auto-generated by factory
        cls.chapter_amsterdam = cls._test_instance.create_test_chapter(published=1)
        cls._created_chapters.append(cls.chapter_amsterdam.name)

        cls.chapter_rotterdam = cls._test_instance.create_test_chapter(published=1)
        cls._created_chapters.append(cls.chapter_rotterdam.name)

        cls.chapter_unpublished = cls._test_instance.create_test_chapter(published=0)
        cls._created_chapters.append(cls.chapter_unpublished.name)

        # Create test members
        cls.member_admin = cls._test_instance.create_test_member(
            first_name="Admin",
            last_name="User",
            email=cls.admin_email,
            birth_date="1980-01-01"
        )
        cls._created_members.append(cls.member_admin.name)

        cls.member_board = cls._test_instance.create_test_member(
            first_name="Board",
            last_name="Member",
            email=cls.board_email,
            birth_date="1985-01-01"
        )
        cls._created_members.append(cls.member_board.name)

        cls.member_regular = cls._test_instance.create_test_member(
            first_name="Regular",
            last_name="Member",
            email=cls.regular_email,
            birth_date="1990-01-01"
        )
        cls._created_members.append(cls.member_regular.name)

        # Create volunteer for board member (required for board positions)
        cls.volunteer_board = cls._test_instance.create_test_volunteer(
            cls.member_board.name,
            email=cls.board_email
        )
        cls._created_volunteers.append(cls.volunteer_board.name)

        # Ensure the "Chair" Chapter Role exists (board_members.chapter_role is a
        # Link to Chapter Role). test_site_2 does not seed it.
        cls._ensure_chapter_role("Chair")

        # Create board membership for Amsterdam
        cls._create_board_membership_class(
            cls.chapter_amsterdam.name,
            cls.volunteer_board.name,
            "Chair"
        )

        # Create users if they don't exist
        cls._create_test_user_with_role_class(cls.admin_email, "System Manager")
        cls._create_test_user_with_role_class(cls.board_email, "Verenigingen Chapter Board Member")
        cls._create_test_user_with_role_class(cls.regular_email, "Verenigingen Member")

        # Link members to users (required for permission service to find member from user)
        # Reload to get latest version after user creation hooks
        cls.member_admin.reload()
        cls.member_admin.user = cls.admin_email
        cls.member_admin.save()

        cls.member_board.reload()
        cls.member_board.user = cls.board_email
        cls.member_board.save()

        cls.member_regular.reload()
        cls.member_regular.user = cls.regular_email
        cls.member_regular.save()

        # FINAL CLEANUP: Reset roles after all hooks have run
        # Hooks like assign_chapter_board_role may have added extra roles
        cls._reset_user_roles(cls.admin_email, "System Manager")
        cls._reset_user_roles(cls.board_email, "Verenigingen Chapter Board Member")
        cls._reset_user_roles(cls.regular_email, "Verenigingen Member")

        # CRITICAL: Commit the data so it persists across test transactions
        frappe.db.commit()

    @classmethod
    def tearDownClass(cls):
        """Clean up test data after all tests"""
        # Clean up in reverse order of dependencies
        try:
            # Delete users created by tests
            for email in cls._created_users:
                if frappe.db.exists("User", email):
                    frappe.delete_doc("User", email, force=True, ignore_permissions=True)

            # Delete volunteers
            for name in cls._created_volunteers:
                if frappe.db.exists("Volunteer", name):
                    frappe.delete_doc("Volunteer", name, force=True, ignore_permissions=True)

            # Delete members and their customers
            for name in cls._created_members:
                if frappe.db.exists("Member", name):
                    member = frappe.get_doc("Member", name)
                    customer = member.customer
                    frappe.delete_doc("Member", name, force=True, ignore_permissions=True)
                    if customer and frappe.db.exists("Customer", customer):
                        frappe.delete_doc("Customer", customer, force=True, ignore_permissions=True)

            # Delete chapters
            for name in cls._created_chapters:
                if frappe.db.exists("Chapter", name):
                    frappe.delete_doc("Chapter", name, force=True, ignore_permissions=True)

            frappe.db.commit()
        except Exception as e:
            frappe.log_error(f"Cleanup error in TestChapterPermissionServiceIntegration: {str(e)}")

        if hasattr(cls, '_test_instance'):
            cls._test_instance.tearDown()
        super().tearDownClass()

    def setUp(self):
        """Set up before each test - clean roles to prevent cross-test pollution.

        IMPORTANT: Role Cleanup Rationale
        ---------------------------------
        Frappe's permission system exhibits cross-test role pollution where additional
        roles (e.g., System Manager, Verenigingen Administrator) can be added to test
        users between test methods. This occurs due to:

        1. Role caching in frappe.get_roles() via Redis (frappe.cache.hget("roles", user))
        2. Hooks like assign_chapter_board_role() that trigger on document saves
        3. Test framework interactions with the permission system

        Without this cleanup, tests that depend on a user having ONLY a specific role
        (like testing that a board member is DENIED access to other chapters) will fail
        because the user unexpectedly has admin roles.

        The _reset_user_roles() method uses direct SQL to bypass caching issues with
        Frappe's add_roles() method, ensuring deterministic test state.
        """
        super().setUp()

        # Reset all test users to their intended single role before each test
        self._reset_user_roles(self.admin_email, "System Manager")
        self._reset_user_roles(self.board_email, "Verenigingen Chapter Board Member")
        self._reset_user_roles(self.regular_email, "Verenigingen Member")

        # Defensively re-assert the Member.user links. Even with per-run unique
        # emails (which eliminate cross-file collisions), a sibling test in the
        # SAME class could in principle mutate these links; this guarantees the
        # permission service can always resolve member-from-user before each test.
        self._reassert_member_user_links()

        frappe.db.commit()

    @classmethod
    def _reassert_member_user_links(cls):
        """Re-assert each test member's user link via direct SQL.

        Uses direct db.set_value (no doc hooks) so it cannot re-trigger
        role-granting hooks that the role reset above just cleaned up.
        """
        # setUpClass invokes _test_instance.setUp() to bootstrap the factory
        # BEFORE the persistent members are created; skip until they exist.
        if not getattr(cls, "member_regular", None):
            return
        for member_name, email in (
            (cls.member_admin.name, cls.admin_email),
            (cls.member_board.name, cls.board_email),
            (cls.member_regular.name, cls.regular_email),
        ):
            if frappe.db.get_value("Member", member_name, "user") != email:
                frappe.db.set_value("Member", member_name, "user", email, update_modified=False)

    @staticmethod
    def _get_db_roles(user):
        """Get actual roles from database, bypassing frappe.get_roles() caching.

        In test mode, frappe.get_roles() can return incorrect results due to
        role caching and test framework interactions. This method queries the
        Has Role table directly for accurate test assertions.
        """
        db_roles = frappe.db.sql("""
            SELECT role FROM `tabHas Role`
            WHERE parent = %s AND parenttype = 'User'
        """, user, as_list=True)
        roles = [r[0] for r in db_roles]
        # Add implicit roles
        roles.extend(["All", "Guest"])
        return roles

    @classmethod
    def _ensure_chapter_role(cls, role_name):
        """Ensure a Chapter Role exists (used as board_members.chapter_role)."""
        if not frappe.db.exists("Chapter Role", role_name):
            frappe.get_doc(
                {
                    "doctype": "Chapter Role",
                    "role_name": role_name,
                    "is_active": 1,
                }
            ).insert(ignore_permissions=True)
            frappe.db.commit()

    @classmethod
    def _create_board_membership_class(cls, chapter_name, volunteer_name, role):
        """Class-level helper to create board membership"""
        chapter_doc = frappe.get_doc("Chapter", chapter_name)
        chapter_doc.append("board_members", {
            "volunteer": volunteer_name,
            "chapter_role": role,
            "from_date": today(),
            "is_active": 1
        })
        chapter_doc.save()

    @classmethod
    def _create_test_user_with_role_class(cls, email, role):
        """Class-level helper to create test user with specific role.

        Uses direct SQL to avoid caching issues with add_roles() which can
        re-save cached roles from previous test runs.
        """
        if frappe.db.exists("User", email):
            # User exists - clear ALL roles (except system ones) using direct SQL
            frappe.db.sql("""
                DELETE FROM `tabHas Role`
                WHERE parent = %s AND parenttype = 'User'
            """, email)

            # Add the specific role using direct SQL to avoid cache issues
            frappe.db.sql("""
                INSERT INTO `tabHas Role` (name, parent, parenttype, parentfield, role)
                VALUES (%s, %s, 'User', 'roles', %s)
            """, (frappe.generate_hash(length=10), email, role))

            # Clear role cache for this user
            frappe.cache.hdel("roles", email)
            frappe.db.commit()
        else:
            user = frappe.get_doc({
                "doctype": "User",
                "email": email,
                "first_name": email.split("@")[0].split(".")[0].title(),
                "enabled": 1,
                "send_welcome_email": 0
            })
            user.insert(ignore_permissions=True)  # OK in test setup

            # Add role via direct SQL to avoid any caching
            frappe.db.sql("""
                INSERT INTO `tabHas Role` (name, parent, parenttype, parentfield, role)
                VALUES (%s, %s, 'User', 'roles', %s)
            """, (frappe.generate_hash(length=10), email, role))

            frappe.cache.hdel("roles", email)
            cls._created_users.append(email)

    @classmethod
    def _reset_user_roles(cls, email, role):
        """Reset a user's roles to just the specified role.

        Called AFTER all setup hooks have run to ensure clean role state.
        Uses direct SQL to avoid any caching or doc-level behavior.
        """
        # Delete ALL existing roles
        frappe.db.sql("""
            DELETE FROM `tabHas Role`
            WHERE parent = %s AND parenttype = 'User'
        """, email)

        # Insert just the specified role
        frappe.db.sql("""
            INSERT INTO `tabHas Role` (name, parent, parenttype, parentfield, role)
            VALUES (%s, %s, 'User', 'roles', %s)
        """, (frappe.generate_hash(length=10), email, role))

        # Clear role cache
        frappe.cache.hdel("roles", email)

    def _create_test_user_with_role(self, email, role):
        """Helper to create test user with specific role"""
        if not frappe.db.exists("User", email):
            user = frappe.get_doc({
                "doctype": "User",
                "email": email,
                "first_name": email.split("@")[0].split(".")[0].title(),
                "enabled": 1,
                "send_welcome_email": 0
            })
            user.insert(ignore_permissions=True)  # OK in test setup
            user.add_roles(role)
            self._created_users.append(email)
            frappe.db.commit()  # Commit so user exists in test

    # ========================================================================
    # ADMIN ROLE TESTS
    # ========================================================================

    def test_admin_gets_unrestricted_query_conditions(self):
        """Test that System Manager gets unrestricted access (empty string)"""
        frappe.set_user(self.admin_email)

        result = get_chapter_permission_service().get_permission_query_conditions(self.admin_email)

        self.assertEqual(result, "", "Admin should have unrestricted access")

    def test_admin_has_document_permission(self):
        """Test that admins have permission for all chapters"""
        frappe.set_user(self.admin_email)

        result = get_chapter_permission_service().has_chapter_permission(
            self.chapter_amsterdam, "read", self.admin_email
        )

        self.assertTrue(result, "Admin should have read access to all chapters")

    # ========================================================================
    # BOARD MEMBER ACCESS TESTS
    # ========================================================================

    def test_board_member_has_access_to_their_chapter(self):
        """Test that board members can access their own chapters"""
        frappe.set_user(self.board_email)

        result = get_chapter_permission_service().has_chapter_permission(
            self.chapter_amsterdam, "read", self.board_email
        )

        self.assertTrue(result, "Board member should have access to their chapter")

    def test_board_member_denied_access_to_other_chapter(self):
        """Test that board members are denied access to chapters they don't belong to"""
        frappe.set_user(self.board_email)
        user = self.board_email

        # Clear cached roles to ensure fresh lookup from database
        frappe.cache.hdel("roles", user)

        result = get_chapter_permission_service().has_chapter_permission(
            self.chapter_rotterdam, "read", user
        )

        self.assertFalse(result, "Board member should be denied access to other chapters")

    def test_board_member_query_includes_their_chapters(self):
        """Test that board members see their chapters + published chapters"""
        frappe.set_user(self.board_email)
        user = self.board_email

        # Patch at the module level where frappe is imported
        with patch.object(frappe, 'get_roles', side_effect=lambda u: self._get_db_roles(u)):
            result = get_chapter_permission_service().get_permission_query_conditions(user)

        # Should include board member's chapter and published condition
        self.assertIn(self.chapter_amsterdam.name, result, "Query should include board member's chapter")
        self.assertIn("published = 1", result, "Query should include published chapters")

    # ========================================================================
    # REGULAR MEMBER ACCESS TESTS
    # ========================================================================

    def test_regular_member_has_read_access(self):
        """Test that regular members have read-only access to published chapters"""
        frappe.set_user(self.regular_email)

        result = get_chapter_permission_service().has_chapter_permission(
            self.chapter_amsterdam, "read", self.regular_email
        )

        self.assertTrue(result, "Regular member should have read access to published chapters")

    def test_regular_member_denied_write_access(self):
        """Test that regular members are denied write access"""
        frappe.set_user(self.regular_email)
        user = self.regular_email

        # Clear cached roles to ensure fresh lookup from database
        frappe.cache.hdel("roles", user)

        result = get_chapter_permission_service().has_chapter_permission(
            self.chapter_amsterdam, "write", user
        )

        self.assertFalse(result, "Regular member should not have write access")

    def test_regular_member_query_shows_only_published(self):
        """Test that regular members only see published chapters in list view"""
        frappe.set_user(self.regular_email)
        user = self.regular_email

        # Patch frappe.get_roles to return actual DB roles
        with patch.object(frappe, 'get_roles', side_effect=lambda u: self._get_db_roles(u)):
            result = get_chapter_permission_service().get_permission_query_conditions(user)

        self.assertEqual(result, "`tabChapter`.published = 1", "Regular members should only see published chapters")

    # ========================================================================
    # API PERMISSION TESTS
    # ========================================================================

    def test_admin_can_view_any_member_board_info(self):
        """Test that admins can view any member's board information"""
        frappe.set_user(self.admin_email)

        result = get_chapter_permission_service().can_user_view_member_board_info(
            self.member_board.name, self.admin_email
        )

        self.assertTrue(result, "Admin should be able to view any member's board info")

    def test_user_can_view_own_board_info(self):
        """Test that users can view their own board information"""
        frappe.set_user(self.board_email)

        result = get_chapter_permission_service().can_user_view_member_board_info(
            self.member_board.name, self.board_email
        )

        self.assertTrue(result, "User should be able to view their own board info")

    def test_admin_can_view_any_chapter_board_history(self):
        """Test that admins can view any chapter's board history"""
        frappe.set_user(self.admin_email)

        result = get_chapter_permission_service().can_user_view_chapter_board_history(
            self.chapter_amsterdam.name, self.admin_email
        )

        self.assertTrue(result, "Admin should be able to view any chapter's board history")

    def test_board_member_can_view_their_chapter_history(self):
        """Test that board members can view their chapter's board history"""
        frappe.set_user(self.board_email)

        result = get_chapter_permission_service().can_user_view_chapter_board_history(
            self.chapter_amsterdam.name, self.board_email
        )

        self.assertTrue(result, "Board member should be able to view their chapter's history")

    def test_board_member_denied_other_chapter_history(self):
        """Test that board members cannot view other chapters' board history"""
        frappe.set_user(self.board_email)
        user = self.board_email

        # Clear cached roles to ensure fresh lookup from database
        frappe.cache.hdel("roles", user)

        result = get_chapter_permission_service().can_user_view_chapter_board_history(
            self.chapter_rotterdam.name, user
        )

        self.assertFalse(result, "Board member should not view other chapters' history")

    # ========================================================================
    # EDGE CASE TESTS
    # ========================================================================

    def test_user_without_member_record_denied_board_info_access(self):
        """Test that users without member records are denied board info access"""
        # Create user without member record. Unique per run so a sibling file
        # cannot leak a Member linked to this email (which would make the user
        # resolvable to a member record and break the "no member record" premise).
        test_email = f"no-member-{frappe.generate_hash(length=8)}@verenigingen.test"
        self._create_test_user_with_role(test_email, "Verenigingen Member")
        frappe.set_user(test_email)

        result = get_chapter_permission_service().can_user_view_member_board_info(
            self.member_board.name, test_email
        )

        self.assertFalse(result, "User without member record should be denied access")

    def test_unpublished_chapter_not_visible_to_regular_members(self):
        """Test that unpublished chapters are not visible to regular members"""
        frappe.set_user(self.regular_email)
        user = self.regular_email

        # Patch frappe.get_roles to return actual DB roles
        with patch.object(frappe, 'get_roles', side_effect=lambda u: self._get_db_roles(u)):
            result = get_chapter_permission_service().has_chapter_permission(
                self.chapter_unpublished, "read", user
            )

            # Regular members should only see published chapters
            # The service returns True for read access, but the query conditions filter it
            query = get_chapter_permission_service().get_permission_query_conditions(user)
            self.assertIn("published = 1", query, "Unpublished chapters should be filtered out")

    # ========================================================================
    # HELPER METHOD TESTS
    # ========================================================================

    def test_get_user_board_chapters_returns_list(self):
        """Test _get_user_board_chapters returns list of chapter names"""
        frappe.set_user(self.board_email)

        chapters = get_chapter_permission_service()._get_user_board_chapters(self.board_email)

        self.assertIn(self.chapter_amsterdam.name, chapters, "Should include Amsterdam chapter")
        self.assertNotIn(self.chapter_rotterdam.name, chapters, "Should not include Rotterdam chapter")

    def test_is_user_board_member_of_chapter_detects_membership(self):
        """Test _is_user_board_member_of_chapter detects board membership"""
        frappe.set_user(self.board_email)

        result = get_chapter_permission_service()._is_user_board_member_of_chapter(
            self.board_email, self.chapter_amsterdam.name
        )

        self.assertTrue(result, "Should detect board membership")

    def test_is_user_board_member_of_chapter_returns_false_for_non_member(self):
        """Test _is_user_board_member_of_chapter returns False for non-members"""
        frappe.set_user(self.regular_email)

        result = get_chapter_permission_service()._is_user_board_member_of_chapter(
            self.regular_email, self.chapter_amsterdam.name
        )

        self.assertFalse(result, "Should not detect board membership for non-member")

    # ========================================================================
    # INTEGRATION TESTS
    # ========================================================================

    def test_full_board_member_permission_flow(self):
        """Integration test: Board member accessing their own chapter"""
        frappe.set_user(self.board_email)
        user = self.board_email

        # Patch frappe.get_roles to return actual DB roles
        with patch.object(frappe, 'get_roles', side_effect=lambda u: self._get_db_roles(u)):
            # Test query conditions
            query = get_chapter_permission_service().get_permission_query_conditions(user)
            self.assertIn(self.chapter_amsterdam.name, query, "Query should include board member's chapter")

            # Test document permission
            has_perm = get_chapter_permission_service().has_chapter_permission(
                self.chapter_amsterdam, "read", user
            )
            self.assertTrue(has_perm, "Board member should have read permission")

    def test_full_regular_member_permission_flow(self):
        """Integration test: Regular member with read-only access"""
        frappe.set_user(self.regular_email)
        user = self.regular_email

        # Patch frappe.get_roles to return actual DB roles
        with patch.object(frappe, 'get_roles', side_effect=lambda u: self._get_db_roles(u)):
            # Test query conditions - should only see published
            query = get_chapter_permission_service().get_permission_query_conditions(user)
            self.assertEqual(query, "`tabChapter`.published = 1", "Regular members should only see published")

            # Test document permission - read allowed, write denied
            self.assertTrue(
                get_chapter_permission_service().has_chapter_permission(
                    self.chapter_amsterdam, "read", user
                ),
                "Regular member should have read access"
            )
            self.assertFalse(
                get_chapter_permission_service().has_chapter_permission(
                    self.chapter_amsterdam, "write", user
                ),
                "Regular member should not have write access"
            )


# Test suite registration
def get_test_suite():
    """Return test suite for pytest discovery"""
    import unittest
    suite = unittest.TestSuite()
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestChapterPermissionServiceIntegration))
    return suite
