# Copyright (c) 2025, Frappe Technologies and contributors
# For license information, please see license.txt

"""
Integration tests for ChapterPermissionService - Real database testing

Tests verify permission logic with actual database operations:
- Admin/staff/board member/regular member access patterns
- Row-level security enforcement
- Permission query generation
- Board membership verification

Uses Enhanced Test Factory for realistic test data.
No database mocking - all operations use real Frappe database.
"""

import frappe
from frappe.utils import now, today
from verenigingen.tests.fixtures.enhanced_test_factory import EnhancedTestCase
from verenigingen.services.chapter.chapter_permission_service import ChapterPermissionService


class TestChapterPermissionServiceIntegration(EnhancedTestCase):
    """Integration test suite for ChapterPermissionService with real database"""

    def setUp(self):
        """Set up test data before each test"""
        super().setUp()

        # Create test chapters - chapter names are auto-generated by factory
        self.chapter_amsterdam = self.create_test_chapter(published=1)

        self.chapter_rotterdam = self.create_test_chapter(published=1)

        self.chapter_unpublished = self.create_test_chapter(published=0)

        # Create test members
        self.member_admin = self.create_test_member(
            first_name="Admin",
            last_name="User",
            email="admin.test@verenigingen.test",
            birth_date="1980-01-01"
        )

        self.member_board = self.create_test_member(
            first_name="Board",
            last_name="Member",
            email="board.test@verenigingen.test",
            birth_date="1985-01-01"
        )

        self.member_regular = self.create_test_member(
            first_name="Regular",
            last_name="Member",
            email="regular.test@verenigingen.test",
            birth_date="1990-01-01"
        )

        # Create volunteer for board member (required for board positions)
        self.volunteer_board = self.create_test_volunteer(
            self.member_board.name,
            email="board.test@verenigingen.test"
        )

        # Create board membership for Amsterdam
        self._create_board_membership(
            self.chapter_amsterdam.name,
            self.volunteer_board.name,
            "Chair"
        )

        # Create users if they don't exist
        self._create_test_user_with_role("admin.test@verenigingen.test", "System Manager")
        self._create_test_user_with_role("board.test@verenigingen.test", "Verenigingen Chapter Board Member")
        self._create_test_user_with_role("regular.test@verenigingen.test", "Verenigingen Member")

    def _create_board_membership(self, chapter_name, volunteer_name, role):
        """Helper to create board membership"""
        chapter_doc = frappe.get_doc("Chapter", chapter_name)
        chapter_doc.append("board_members", {
            "volunteer": volunteer_name,
            "chapter_role": role,
            "from_date": today(),
            "is_active": 1
        })
        chapter_doc.save()

    def _create_test_user_with_role(self, email, role):
        """Helper to create test user with specific role"""
        if not frappe.db.exists("User", email):
            user = frappe.get_doc({
                "doctype": "User",
                "email": email,
                "first_name": email.split("@")[0].split(".")[0].title(),
                "enabled": 1,
                "send_welcome_email": 0
            })
            user.insert(ignore_permissions=True)  # OK in test setup
            user.add_roles(role)

    # ========================================================================
    # ADMIN ROLE TESTS
    # ========================================================================

    def test_admin_gets_unrestricted_query_conditions(self):
        """Test that System Manager gets unrestricted access (empty string)"""
        frappe.set_user("admin.test@verenigingen.test")

        result = ChapterPermissionService.get_permission_query_conditions("admin.test@verenigingen.test")

        self.assertEqual(result, "", "Admin should have unrestricted access")

    def test_admin_has_document_permission(self):
        """Test that admins have permission for all chapters"""
        frappe.set_user("admin.test@verenigingen.test")

        result = ChapterPermissionService.has_chapter_permission(
            self.chapter_amsterdam, "read", "admin.test@verenigingen.test"
        )

        self.assertTrue(result, "Admin should have read access to all chapters")

    # ========================================================================
    # BOARD MEMBER ACCESS TESTS
    # ========================================================================

    def test_board_member_has_access_to_their_chapter(self):
        """Test that board members can access their own chapters"""
        frappe.set_user("board.test@verenigingen.test")

        result = ChapterPermissionService.has_chapter_permission(
            self.chapter_amsterdam, "read", "board.test@verenigingen.test"
        )

        self.assertTrue(result, "Board member should have access to their chapter")

    def test_board_member_denied_access_to_other_chapter(self):
        """Test that board members are denied access to chapters they don't belong to"""
        frappe.set_user("board.test@verenigingen.test")

        result = ChapterPermissionService.has_chapter_permission(
            self.chapter_rotterdam, "read", "board.test@verenigingen.test"
        )

        self.assertFalse(result, "Board member should be denied access to other chapters")

    def test_board_member_query_includes_their_chapters(self):
        """Test that board members see their chapters + published chapters"""
        frappe.set_user("board.test@verenigingen.test")

        result = ChapterPermissionService.get_permission_query_conditions("board.test@verenigingen.test")

        # Should include board member's chapter and published condition
        self.assertIn(self.chapter_amsterdam.name, result, "Query should include board member's chapter")
        self.assertIn("published = 1", result, "Query should include published chapters")

    # ========================================================================
    # REGULAR MEMBER ACCESS TESTS
    # ========================================================================

    def test_regular_member_has_read_access(self):
        """Test that regular members have read-only access to published chapters"""
        frappe.set_user("regular.test@verenigingen.test")

        result = ChapterPermissionService.has_chapter_permission(
            self.chapter_amsterdam, "read", "regular.test@verenigingen.test"
        )

        self.assertTrue(result, "Regular member should have read access to published chapters")

    def test_regular_member_denied_write_access(self):
        """Test that regular members are denied write access"""
        frappe.set_user("regular.test@verenigingen.test")

        result = ChapterPermissionService.has_chapter_permission(
            self.chapter_amsterdam, "write", "regular.test@verenigingen.test"
        )

        self.assertFalse(result, "Regular member should not have write access")

    def test_regular_member_query_shows_only_published(self):
        """Test that regular members only see published chapters in list view"""
        frappe.set_user("regular.test@verenigingen.test")

        result = ChapterPermissionService.get_permission_query_conditions("regular.test@verenigingen.test")

        self.assertEqual(result, "`tabChapter`.published = 1", "Regular members should only see published chapters")

    # ========================================================================
    # API PERMISSION TESTS
    # ========================================================================

    def test_admin_can_view_any_member_board_info(self):
        """Test that admins can view any member's board information"""
        frappe.set_user("admin.test@verenigingen.test")

        result = ChapterPermissionService.can_user_view_member_board_info(
            self.member_board.name, "admin.test@verenigingen.test"
        )

        self.assertTrue(result, "Admin should be able to view any member's board info")

    def test_user_can_view_own_board_info(self):
        """Test that users can view their own board information"""
        frappe.set_user("board.test@verenigingen.test")

        result = ChapterPermissionService.can_user_view_member_board_info(
            self.member_board.name, "board.test@verenigingen.test"
        )

        self.assertTrue(result, "User should be able to view their own board info")

    def test_admin_can_view_any_chapter_board_history(self):
        """Test that admins can view any chapter's board history"""
        frappe.set_user("admin.test@verenigingen.test")

        result = ChapterPermissionService.can_user_view_chapter_board_history(
            self.chapter_amsterdam.name, "admin.test@verenigingen.test"
        )

        self.assertTrue(result, "Admin should be able to view any chapter's board history")

    def test_board_member_can_view_their_chapter_history(self):
        """Test that board members can view their chapter's board history"""
        frappe.set_user("board.test@verenigingen.test")

        result = ChapterPermissionService.can_user_view_chapter_board_history(
            self.chapter_amsterdam.name, "board.test@verenigingen.test"
        )

        self.assertTrue(result, "Board member should be able to view their chapter's history")

    def test_board_member_denied_other_chapter_history(self):
        """Test that board members cannot view other chapters' board history"""
        frappe.set_user("board.test@verenigingen.test")

        result = ChapterPermissionService.can_user_view_chapter_board_history(
            self.chapter_rotterdam.name, "board.test@verenigingen.test"
        )

        self.assertFalse(result, "Board member should not view other chapters' history")

    # ========================================================================
    # EDGE CASE TESTS
    # ========================================================================

    def test_user_without_member_record_denied_board_info_access(self):
        """Test that users without member records are denied board info access"""
        # Create user without member record
        test_email = "no.member@verenigingen.test"
        self._create_test_user_with_role(test_email, "Verenigingen Member")
        frappe.set_user(test_email)

        result = ChapterPermissionService.can_user_view_member_board_info(
            self.member_board.name, test_email
        )

        self.assertFalse(result, "User without member record should be denied access")

    def test_unpublished_chapter_not_visible_to_regular_members(self):
        """Test that unpublished chapters are not visible to regular members"""
        frappe.set_user("regular.test@verenigingen.test")

        result = ChapterPermissionService.has_chapter_permission(
            self.chapter_unpublished, "read", "regular.test@verenigingen.test"
        )

        # Regular members should only see published chapters
        # The service returns True for read access, but the query conditions filter it
        query = ChapterPermissionService.get_permission_query_conditions("regular.test@verenigingen.test")
        self.assertIn("published = 1", query, "Unpublished chapters should be filtered out")

    # ========================================================================
    # HELPER METHOD TESTS
    # ========================================================================

    def test_get_user_board_chapters_returns_list(self):
        """Test _get_user_board_chapters returns list of chapter names"""
        frappe.set_user("board.test@verenigingen.test")

        chapters = ChapterPermissionService._get_user_board_chapters("board.test@verenigingen.test")

        self.assertIn(self.chapter_amsterdam.name, chapters, "Should include Amsterdam chapter")
        self.assertNotIn(self.chapter_rotterdam.name, chapters, "Should not include Rotterdam chapter")

    def test_is_user_board_member_of_chapter_detects_membership(self):
        """Test _is_user_board_member_of_chapter detects board membership"""
        frappe.set_user("board.test@verenigingen.test")

        result = ChapterPermissionService._is_user_board_member_of_chapter(
            "board.test@verenigingen.test", self.chapter_amsterdam.name
        )

        self.assertTrue(result, "Should detect board membership")

    def test_is_user_board_member_of_chapter_returns_false_for_non_member(self):
        """Test _is_user_board_member_of_chapter returns False for non-members"""
        frappe.set_user("regular.test@verenigingen.test")

        result = ChapterPermissionService._is_user_board_member_of_chapter(
            "regular.test@verenigingen.test", self.chapter_amsterdam.name
        )

        self.assertFalse(result, "Should not detect board membership for non-member")

    # ========================================================================
    # INTEGRATION TESTS
    # ========================================================================

    def test_full_board_member_permission_flow(self):
        """Integration test: Board member accessing their own chapter"""
        frappe.set_user("board.test@verenigingen.test")

        # Test query conditions
        query = ChapterPermissionService.get_permission_query_conditions("board.test@verenigingen.test")
        self.assertIn(self.chapter_amsterdam.name, query, "Query should include board member's chapter")

        # Test document permission
        has_perm = ChapterPermissionService.has_chapter_permission(
            self.chapter_amsterdam, "read", "board.test@verenigingen.test"
        )
        self.assertTrue(has_perm, "Board member should have read permission")

    def test_full_regular_member_permission_flow(self):
        """Integration test: Regular member with read-only access"""
        frappe.set_user("regular.test@verenigingen.test")

        # Test query conditions - should only see published
        query = ChapterPermissionService.get_permission_query_conditions("regular.test@verenigingen.test")
        self.assertEqual(query, "`tabChapter`.published = 1", "Regular members should only see published")

        # Test document permission - read allowed, write denied
        self.assertTrue(
            ChapterPermissionService.has_chapter_permission(
                self.chapter_amsterdam, "read", "regular.test@verenigingen.test"
            ),
            "Regular member should have read access"
        )
        self.assertFalse(
            ChapterPermissionService.has_chapter_permission(
                self.chapter_amsterdam, "write", "regular.test@verenigingen.test"
            ),
            "Regular member should not have write access"
        )


# Test suite registration
def get_test_suite():
    """Return test suite for pytest discovery"""
    import unittest
    suite = unittest.TestSuite()
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestChapterPermissionServiceIntegration))
    return suite
