"""
Add new notification types for team member, chapter member, and dues amendment notifications.

This patch adds notification keys that were introduced for:
- Team member added/removed notifications
- Chapter member joined/left notifications
- Member status change notifications
- Dues amendment approved/rejected notifications
"""

import frappe


def execute():
    """Add new notification types to Verenigingen Email Configuration if they don't exist."""
    # Check if Verenigingen Email Configuration exists
    if not frappe.db.exists("DocType", "Verenigingen Email Configuration"):
        return

    # NOTE: Verenigingen Email Configuration is a Single with no mandatory
    # fields, so frappe.get_single() below always succeeds regardless of
    # whether it has been saved before. A second
    # `frappe.db.exists("Verenigingen Email Configuration", "Verenigingen
    # Email Configuration")` guard used to sit here, but that check is
    # unconditionally truthy for a Single (dt == dn short-circuits in
    # frappe.db.exists) and so was never able to skip this patch (#889).
    config = frappe.get_single("Verenigingen Email Configuration")

    new_types = [
        {
            "notification_key": "team_member_added",
            "label": "Team Member Added",
            "category": "Volunteer",
            "enabled": 1,
            "priority": "Low",
            "cooldown_minutes": 60,
            "email_template": "team_role_notification",
            "recipient_policy": "Document-Field",
            "recipient_field": "volunteer.email",
            "description": "Email sent when volunteer is added to a team",
        },
        {
            "notification_key": "team_member_removed",
            "label": "Team Member Removed",
            "category": "Volunteer",
            "enabled": 1,
            "priority": "Low",
            "cooldown_minutes": 60,
            "email_template": "team_role_notification",
            "recipient_policy": "Document-Field",
            "recipient_field": "volunteer.email",
            "description": "Email sent when volunteer is removed from a team",
        },
        {
            "notification_key": "team_role_changed",
            "label": "Team Role Changed",
            "category": "Volunteer",
            "enabled": 1,
            "priority": "Low",
            "cooldown_minutes": 60,
            "email_template": "team_role_notification",
            "recipient_policy": "Document-Field",
            "recipient_field": "volunteer.email",
            "description": "Email sent when volunteer's team role is changed",
        },
        {
            "notification_key": "team_settings_changed",
            "label": "Team Settings Changed",
            "category": "Volunteer",
            "enabled": 1,
            "priority": "Low",
            "cooldown_minutes": 60,
            "email_template": "team_role_notification",
            "recipient_policy": "Document-Field",
            "recipient_field": "volunteer.email",
            "description": "Email sent when team settings are updated",
        },
        {
            "notification_key": "team_leadership_changed",
            "label": "Team Leadership Changed",
            "category": "Volunteer",
            "enabled": 1,
            "priority": "Medium",
            "cooldown_minutes": 60,
            "email_template": "team_role_notification",
            "recipient_policy": "Document-Field",
            "recipient_field": "volunteer.email",
            "description": "Email sent when team leadership changes",
        },
        {
            "notification_key": "chapter_member_joined",
            "label": "Member Joined Chapter",
            "category": "Chapter",
            "enabled": 1,
            "priority": "Low",
            "cooldown_minutes": 60,
            "email_template": "chapter_board_notification",
            "recipient_policy": "Document-Field",
            "recipient_field": "member.email",
            "description": "Welcome email sent when member joins a chapter",
        },
        {
            "notification_key": "chapter_member_left",
            "label": "Member Left Chapter",
            "category": "Chapter",
            "enabled": 1,
            "priority": "Low",
            "cooldown_minutes": 60,
            "email_template": "chapter_board_notification",
            "recipient_policy": "Document-Field",
            "recipient_field": "member.email",
            "description": "Farewell email sent when member leaves a chapter",
        },
        {
            "notification_key": "chapter_board_role_changed",
            "label": "Chapter Board Role Changed",
            "category": "Chapter",
            "enabled": 1,
            "priority": "Medium",
            "cooldown_minutes": 60,
            "email_template": "chapter_board_notification",
            "recipient_policy": "Document-Field",
            "recipient_field": "volunteer.email",
            "description": "Email sent when a board member's role is updated",
        },
        {
            "notification_key": "chapter_settings_changed",
            "label": "Chapter Settings Changed",
            "category": "Chapter",
            "enabled": 1,
            "priority": "Low",
            "cooldown_minutes": 60,
            "email_template": "chapter_board_notification",
            "recipient_policy": "Document-Field",
            "recipient_field": "board_member.email",
            "description": "Email sent to board members when chapter settings are updated",
        },
        # Member Status Notifications
        {
            "notification_key": "member_activated",
            "label": "Membership Activated",
            "category": "Member",
            "enabled": 1,
            "priority": "Medium",
            "cooldown_minutes": 60,
            "email_template": "member_lifecycle_notification",
            "recipient_policy": "Document-Field",
            "recipient_field": "email",
            "description": "Email sent when member status changes to Active",
        },
        {
            "notification_key": "member_suspended",
            "label": "Membership Suspended",
            "category": "Member",
            "enabled": 1,
            "priority": "High",
            "cooldown_minutes": 60,
            "email_template": "member_lifecycle_notification",
            "recipient_policy": "Document-Field",
            "recipient_field": "email",
            "description": "Email sent when member status changes to Suspended",
        },
        {
            "notification_key": "member_terminated",
            "label": "Membership Terminated",
            "category": "Member",
            "enabled": 1,
            "priority": "High",
            "cooldown_minutes": 60,
            "email_template": "member_lifecycle_notification",
            "recipient_policy": "Document-Field",
            "recipient_field": "email",
            "description": "Email sent when membership is terminated",
        },
        {
            "notification_key": "member_status_change",
            "label": "Member Status Change",
            "category": "Member",
            "enabled": 1,
            "priority": "Low",
            "cooldown_minutes": 60,
            "email_template": "member_lifecycle_notification",
            "recipient_policy": "Document-Field",
            "recipient_field": "email",
            "description": "Generic notification for other member status changes",
        },
        # Dues Amendment Notifications
        {
            "notification_key": "dues_amendment_approved",
            "label": "Dues Amendment Approved",
            "category": "Member",
            "enabled": 1,
            "priority": "Medium",
            "cooldown_minutes": 0,
            "email_template": "amendment_approved",
            "recipient_policy": "Document-Field",
            "recipient_field": "requested_by",
            "description": "Email sent when a dues adjustment request is approved",
        },
        {
            "notification_key": "dues_amendment_rejected",
            "label": "Dues Amendment Rejected",
            "category": "Member",
            "enabled": 1,
            "priority": "Medium",
            "cooldown_minutes": 0,
            "email_template": "amendment_rejected",
            "recipient_policy": "Document-Field",
            "recipient_field": "requested_by",
            "description": "Email sent when a dues adjustment request is rejected",
        },
        # Payment Failure Notifications
        {
            "notification_key": "payment_failure_first",
            "label": "Payment Failed (First Notice)",
            "category": "Payment",
            "enabled": 1,
            "priority": "Medium",
            "cooldown_minutes": 1440,
            "email_template": "payment_failure_first",
            "recipient_policy": "Document-Field",
            "recipient_field": "email",
            "description": "Email sent on first payment failure",
        },
        {
            "notification_key": "payment_failure_second",
            "label": "Payment Failed (Second Notice)",
            "category": "Payment",
            "enabled": 1,
            "priority": "High",
            "cooldown_minutes": 1440,
            "email_template": "payment_failure_second",
            "recipient_policy": "Document-Field",
            "recipient_field": "email",
            "description": "Email sent on second payment failure",
        },
        {
            "notification_key": "payment_failure_final",
            "label": "Payment Failed (Final Notice)",
            "category": "Payment",
            "enabled": 1,
            "priority": "High",
            "cooldown_minutes": 0,
            "email_template": "payment_failure_final",
            "recipient_policy": "Document-Field",
            "recipient_field": "email",
            "description": "Final notice after multiple payment failures",
        },
        # Subscription Status Notifications
        {
            "notification_key": "subscription_cancelled",
            "label": "Subscription Cancelled",
            "category": "Payment",
            "enabled": 1,
            "priority": "High",
            "cooldown_minutes": 0,
            "email_template": "subscription_cancelled",
            "recipient_policy": "Document-Field",
            "recipient_field": "email",
            "description": "Email sent when payment subscription is cancelled",
        },
        {
            "notification_key": "subscription_suspended",
            "label": "Subscription Suspended",
            "category": "Payment",
            "enabled": 1,
            "priority": "High",
            "cooldown_minutes": 0,
            "email_template": "subscription_suspended",
            "recipient_policy": "Document-Field",
            "recipient_field": "email",
            "description": "Email sent when payment subscription is suspended",
        },
        # Periodic Donation Notifications
        {
            "notification_key": "periodic_donation_confirmation",
            "label": "Periodic Donation Confirmed",
            "category": "Payment",
            "enabled": 1,
            "priority": "Medium",
            "cooldown_minutes": 0,
            "email_template": "periodic_agreement_confirmation",
            "recipient_policy": "Document-Field",
            "recipient_field": "donor.donor_email",
            "description": "Confirmation email for new periodic donation agreement",
        },
        {
            "notification_key": "periodic_donation_expiry",
            "label": "Periodic Donation Expiring",
            "category": "Payment",
            "enabled": 1,
            "priority": "Medium",
            "cooldown_minutes": 1440,
            "email_template": "periodic_agreement_expiry",
            "recipient_policy": "Document-Field",
            "recipient_field": "donor.donor_email",
            "description": "Warning email when periodic donation is about to expire",
        },
        {
            "notification_key": "periodic_donation_cancellation",
            "label": "Periodic Donation Cancelled",
            "category": "Payment",
            "enabled": 1,
            "priority": "Medium",
            "cooldown_minutes": 0,
            "email_template": "periodic_agreement_cancellation",
            "recipient_policy": "Document-Field",
            "recipient_field": "donor.donor_email",
            "description": "Confirmation email when periodic donation is cancelled",
        },
        # ANBI Notifications
        {
            "notification_key": "anbi_consent_request",
            "label": "ANBI Consent Request",
            "category": "Payment",
            "enabled": 1,
            "priority": "Low",
            "cooldown_minutes": 10080,
            "email_template": "anbi_consent_request",
            "recipient_policy": "Document-Field",
            "recipient_field": "donor.donor_email",
            "description": "Request for ANBI tax benefit consent from donor",
        },
        # Analytics Notifications
        {
            "notification_key": "analytics_alert",
            "label": "Analytics Alert",
            "category": "System",
            "enabled": 1,
            "priority": "Medium",
            "cooldown_minutes": 60,
            "email_template": "analytics_alert",
            "recipient_policy": "Role",
            "recipient_roles": ["Verenigingen Staff"],
            "description": "Alert triggered by analytics monitoring rules",
        },
        # Membership Renewal
        {
            "notification_key": "membership_renewal_reminder",
            "label": "Membership Renewal Reminder",
            "category": "Member",
            "enabled": 1,
            "priority": "Medium",
            "cooldown_minutes": 1440,
            "email_template": "membership_renewal_reminder",
            "recipient_policy": "Document-Field",
            "recipient_field": "email",
            "description": "Reminder email sent before membership expires",
        },
        # Payment Plan Notifications
        {
            "notification_key": "payment_plan_request",
            "label": "Payment Plan Request",
            "category": "Payment",
            "enabled": 1,
            "priority": "Medium",
            "cooldown_minutes": 0,
            "email_template": "payment_notification",
            "recipient_policy": "Role",
            "recipient_roles": ["Verenigingen Staff"],
            "description": "Admin notification when member requests payment plan",
        },
        {
            "notification_key": "payment_plan_approved",
            "label": "Payment Plan Approved",
            "category": "Payment",
            "enabled": 1,
            "priority": "Medium",
            "cooldown_minutes": 0,
            "email_template": "payment_notification",
            "recipient_policy": "Document-Field",
            "recipient_field": "member.email",
            "description": "Email sent when payment plan is approved",
        },
        {
            "notification_key": "payment_plan_rejected",
            "label": "Payment Plan Rejected",
            "category": "Payment",
            "enabled": 1,
            "priority": "Medium",
            "cooldown_minutes": 0,
            "email_template": "payment_notification",
            "recipient_policy": "Document-Field",
            "recipient_field": "member.email",
            "description": "Email sent when payment plan is rejected",
        },
        # Member Application Notifications
        {
            "notification_key": "member_application_rejected",
            "label": "Membership Application Rejected",
            "category": "Member",
            "enabled": 1,
            "priority": "Medium",
            "cooldown_minutes": 0,
            "email_template": "member_rejection",
            "recipient_policy": "Document-Field",
            "recipient_field": "email",
            "description": "Email sent when membership application is rejected",
        },
        {
            "notification_key": "member_application_confirmation",
            "label": "Membership Application Received",
            "category": "Member",
            "enabled": 1,
            "priority": "Low",
            "cooldown_minutes": 0,
            "email_template": "membership_application_confirmation",
            "recipient_policy": "Document-Field",
            "recipient_field": "email",
            "description": "Confirmation email when membership application is received",
        },
        # Payment Reminder Notifications
        {
            "notification_key": "payment_reminder_friendly",
            "label": "Payment Reminder (Friendly)",
            "category": "Payment",
            "enabled": 1,
            "priority": "Low",
            "cooldown_minutes": 4320,
            "email_template": "payment_reminder",
            "recipient_policy": "Document-Field",
            "recipient_field": "email",
            "description": "Friendly reminder for upcoming or slightly overdue payment",
        },
        {
            "notification_key": "payment_reminder_urgent",
            "label": "Payment Reminder (Urgent)",
            "category": "Payment",
            "enabled": 1,
            "priority": "High",
            "cooldown_minutes": 1440,
            "email_template": "payment_reminder_urgent",
            "recipient_policy": "Document-Field",
            "recipient_field": "email",
            "description": "Urgent reminder for significantly overdue payment",
        },
        # Payment Success Notification
        {
            "notification_key": "payment_success",
            "label": "Payment Received",
            "category": "Payment",
            "enabled": 1,
            "priority": "Low",
            "cooldown_minutes": 0,
            "email_template": "payment_notification",
            "recipient_policy": "Document-Field",
            "recipient_field": "member.email",
            "description": "Confirmation email when payment is successfully received",
        },
        # System Alerts
        {
            "notification_key": "payment_history_failure_alert",
            "label": "Payment History Failure Alert",
            "category": "System",
            "enabled": 1,
            "priority": "High",
            "cooldown_minutes": 60,
            "email_template": "payment_notification",
            "recipient_policy": "Role-Based",
            "recipient_roles": "System Manager",
            "description": "Alert when payment history queue has high failure rate",
        },
        {
            "notification_key": "payment_history_critical_error",
            "label": "Payment History Critical Error",
            "category": "System",
            "enabled": 1,
            "priority": "Critical",
            "cooldown_minutes": 0,
            "email_template": "payment_notification",
            "recipient_policy": "Role-Based",
            "recipient_roles": "System Manager",
            "description": "Critical alert when payment history queue processing fails completely",
        },
        {
            "notification_key": "security_policy_digest",
            "label": "Security Policy Change Digest",
            "category": "System",
            "enabled": 1,
            "priority": "High",
            "cooldown_minutes": 60,
            "email_template": "payment_notification",
            "recipient_policy": "Role-Based",
            "recipient_roles": "System Manager",
            "description": "Aggregated digest of Critical Operation Rule changes (sent hourly)",
        },
        {
            "notification_key": "dues_schedule_auto_creation_summary",
            "label": "Dues Schedule Auto-Creation Summary",
            "category": "System",
            "enabled": 1,
            "priority": "Medium",
            "cooldown_minutes": 60,
            "email_template": "payment_notification",
            "recipient_policy": "Role-Based",
            "recipient_roles": "System Manager, Verenigingen Administrator",
            "description": "Summary email after scheduled dues schedule auto-creation task runs",
        },
        {
            "notification_key": "dues_schedule_manual_creation",
            "label": "Dues Schedule Manual Creation",
            "category": "System",
            "enabled": 1,
            "priority": "Medium",
            "cooldown_minutes": 0,
            "email_template": "payment_notification",
            "recipient_policy": "Role-Based",
            "recipient_roles": "System Manager, Verenigingen Administrator",
            "description": "Notification when dues schedules are manually created via admin interface",
        },
        {
            "notification_key": "ponto_payment_link_request",
            "label": "Ponto Payment Link Request",
            "category": "Payment",
            "enabled": 1,
            "priority": "Medium",
            "cooldown_minutes": 0,
            "email_template": "payment_notification",
            "recipient_policy": "Document-Field",
            "recipient_field": "member.email",
            "description": "Payment request email sent to customer with Ponto payment link",
        },
    ]

    existing_keys = {nt.notification_key for nt in config.notification_types}
    added = 0

    for nt in new_types:
        if nt["notification_key"] not in existing_keys:
            config.append("notification_types", nt)
            added += 1

    if added > 0:
        config.flags.ignore_permissions = True
        config.save()
        frappe.db.commit()

    frappe.logger().info(f"Added {added} new notification types to Verenigingen Email Configuration")
