#!/usr/bin/env python3
"""
Export all verenigingen and e-boekhouden custom fields to fixtures

This script exports all custom fields that should be managed by the verenigingen app
to the custom_field.json fixture file.
"""

import json
from pathlib import Path

# All 16 Verenigingen module custom fields from database
verenigingen_fields = [
    {
        "allow_in_quick_entry": 0,
        "allow_on_submit": 0,
        "bold": 0,
        "collapsible": 0,
        "collapsible_depends_on": None,
        "columns": 0,
        "default": None,
        "depends_on": None,
        "description": "Bank transaction references related to this batch",
        "docstatus": 0,
        "doctype": "Custom Field",
        "dt": "Direct Debit Batch",
        "fetch_from": None,
        "fetch_if_empty": 0,
        "fieldname": "custom_related_bank_transactions",
        "fieldtype": "Long Text",
        "hidden": 0,
        "hide_border": 0,
        "hide_days": 0,
        "hide_seconds": 0,
        "ignore_user_permissions": 0,
        "ignore_xss_filter": 0,
        "in_global_search": 0,
        "in_list_view": 0,
        "in_preview": 0,
        "in_standard_filter": 0,
        "insert_after": "custom_reconciliation_status",
        "is_system_generated": 0,
        "is_virtual": 0,
        "label": "Related Bank Transactions",
        "length": 0,
        "link_filters": None,
        "mandatory_depends_on": None,
        "modified": "2025-08-01 20:32:02.221243",
        "module": "Verenigingen",
        "name": "Direct Debit Batch-custom_related_bank_transactions",
        "no_copy": 0,
        "non_negative": 0,
        "options": "",
        "permlevel": 0,
        "placeholder": None,
        "precision": "",
        "print_hide": 0,
        "print_hide_if_no_value": 0,
        "print_width": None,
        "read_only": 0,
        "read_only_depends_on": None,
        "report_hide": 0,
        "reqd": 0,
        "search_index": 0,
        "show_dashboard": 0,
        "sort_options": 0,
        "translatable": 0,
        "unique": 0,
        "width": None
    },
    {
        "allow_in_quick_entry": 0,
        "allow_on_submit": 0,
        "bold": 0,
        "collapsible": 0,
        "collapsible_depends_on": None,
        "columns": 0,
        "default": "",
        "depends_on": None,
        "description": "Related SEPA Direct Debit Batch",
        "docstatus": 0,
        "doctype": "Custom Field",
        "dt": "Bank Transaction",
        "fetch_from": None,
        "fetch_if_empty": 0,
        "fieldname": "custom_sepa_batch",
        "fieldtype": "Link",
        "hidden": 0,
        "hide_border": 0,
        "hide_days": 0,
        "hide_seconds": 0,
        "ignore_user_permissions": 0,
        "ignore_xss_filter": 0,
        "in_global_search": 0,
        "in_list_view": 0,
        "in_preview": 0,
        "in_standard_filter": 0,
        "insert_after": "bank_account",
        "is_system_generated": 0,
        "is_virtual": 0,
        "label": "SEPA Batch",
        "length": 0,
        "link_filters": None,
        "mandatory_depends_on": None,
        "modified": "2025-08-01 20:29:38.644574",
        "module": "Verenigingen",
        "name": "Bank Transaction-custom_sepa_batch",
        "no_copy": 0,
        "non_negative": 0,
        "options": "SEPA Direct Debit Batch",
        "permlevel": 0,
        "placeholder": None,
        "precision": "",
        "print_hide": 0,
        "print_hide_if_no_value": 0,
        "print_width": None,
        "read_only": 0,
        "read_only_depends_on": None,
        "report_hide": 0,
        "reqd": 0,
        "search_index": 0,
        "show_dashboard": 0,
        "sort_options": 0,
        "translatable": 0,
        "unique": 0,
        "width": None
    },
    {
        "allow_in_quick_entry": 0,
        "allow_on_submit": 0,
        "bold": 0,
        "collapsible": 0,
        "collapsible_depends_on": None,
        "columns": 0,
        "default": None,
        "depends_on": "eval:doc.is_membership_invoice",
        "description": "Association member linked to this invoice",
        "docstatus": 0,
        "doctype": "Custom Field",
        "dt": "Sales Invoice",
        "fetch_from": "customer.member",
        "fetch_if_empty": 0,
        "fieldname": "member",
        "fieldtype": "Link",
        "hidden": 0,
        "hide_border": 0,
        "hide_days": 0,
        "hide_seconds": 0,
        "ignore_user_permissions": 0,
        "ignore_xss_filter": 0,
        "in_global_search": 0,
        "in_list_view": 0,
        "in_preview": 0,
        "in_standard_filter": 1,
        "insert_after": "membership",
        "is_system_generated": 1,
        "is_virtual": 0,
        "label": "Member",
        "length": 0,
        "link_filters": None,
        "mandatory_depends_on": None,
        "modified": "2025-08-01 18:21:00.678666",
        "module": "Verenigingen",
        "name": "Sales Invoice-member",
        "no_copy": 0,
        "non_negative": 0,
        "options": "Member",
        "permlevel": 0,
        "placeholder": None,
        "precision": "",
        "print_hide": 0,
        "print_hide_if_no_value": 0,
        "print_width": None,
        "read_only": 1,
        "read_only_depends_on": None,
        "report_hide": 0,
        "reqd": 0,
        "search_index": 0,
        "show_dashboard": 0,
        "sort_options": 0,
        "translatable": 0,
        "unique": 0,
        "width": None
    },
    {
        "allow_in_quick_entry": 0,
        "allow_on_submit": 1,
        "bold": 0,
        "collapsible": 0,
        "collapsible_depends_on": None,
        "columns": 0,
        "default": None,
        "depends_on": "eval:doc.is_membership_invoice",
        "description": "Links invoice to specific membership record",
        "docstatus": 0,
        "doctype": "Custom Field",
        "dt": "Sales Invoice",
        "fetch_from": None,
        "fetch_if_empty": 0,
        "fieldname": "membership",
        "fieldtype": "Link",
        "hidden": 0,
        "hide_border": 0,
        "hide_days": 0,
        "hide_seconds": 0,
        "ignore_user_permissions": 0,
        "ignore_xss_filter": 0,
        "in_global_search": 0,
        "in_list_view": 0,
        "in_preview": 0,
        "in_standard_filter": 0,
        "insert_after": "is_membership_invoice",
        "is_system_generated": 1,
        "is_virtual": 0,
        "label": "Membership",
        "length": 0,
        "link_filters": None,
        "mandatory_depends_on": None,
        "modified": "2025-08-01 18:21:00.585122",
        "module": "Verenigingen",
        "name": "Sales Invoice-membership",
        "no_copy": 1,
        "non_negative": 0,
        "options": "Membership",
        "permlevel": 0,
        "placeholder": None,
        "precision": "",
        "print_hide": 0,
        "print_hide_if_no_value": 0,
        "print_width": None,
        "read_only": 1,
        "read_only_depends_on": None,
        "report_hide": 0,
        "reqd": 0,
        "search_index": 0,
        "show_dashboard": 0,
        "sort_options": 0,
        "translatable": 0,
        "unique": 0,
        "width": None
    },
    {
        "allow_in_quick_entry": 0,
        "allow_on_submit": 0,
        "bold": 0,
        "collapsible": 0,
        "collapsible_depends_on": None,
        "columns": 0,
        "default": "0",
        "depends_on": None,
        "description": None,
        "docstatus": 0,
        "doctype": "Custom Field",
        "dt": "Sales Invoice",
        "fetch_from": None,
        "fetch_if_empty": 0,
        "fieldname": "is_membership_invoice",
        "fieldtype": "Check",
        "hidden": 0,
        "hide_border": 0,
        "hide_days": 0,
        "hide_seconds": 0,
        "ignore_user_permissions": 0,
        "ignore_xss_filter": 0,
        "in_global_search": 0,
        "in_list_view": 0,
        "in_preview": 0,
        "in_standard_filter": 0,
        "insert_after": "membership_dues_section",
        "is_system_generated": 1,
        "is_virtual": 0,
        "label": "Is Membership Invoice",
        "length": 0,
        "link_filters": None,
        "mandatory_depends_on": None,
        "modified": "2025-08-01 18:21:00.446171",
        "module": "Verenigingen",
        "name": "Sales Invoice-is_membership_invoice",
        "no_copy": 0,
        "non_negative": 0,
        "options": None,
        "permlevel": 0,
        "placeholder": None,
        "precision": "",
        "print_hide": 0,
        "print_hide_if_no_value": 0,
        "print_width": None,
        "read_only": 0,
        "read_only_depends_on": None,
        "report_hide": 0,
        "reqd": 0,
        "search_index": 0,
        "show_dashboard": 0,
        "sort_options": 0,
        "translatable": 0,
        "unique": 0,
        "width": None
    },
    {
        "allow_in_quick_entry": 0,
        "allow_on_submit": 0,
        "bold": 0,
        "collapsible": 0,
        "collapsible_depends_on": None,
        "columns": 0,
        "default": None,
        "depends_on": None,
        "description": "Link to original donor record for nonprofit operations",
        "docstatus": 0,
        "doctype": "Custom Field",
        "dt": "Customer",
        "fetch_from": None,
        "fetch_if_empty": 0,
        "fieldname": "custom_donor_reference",
        "fieldtype": "Link",
        "hidden": 0,
        "hide_border": 0,
        "hide_days": 0,
        "hide_seconds": 0,
        "ignore_user_permissions": 0,
        "ignore_xss_filter": 0,
        "in_global_search": 0,
        "in_list_view": 0,
        "in_preview": 0,
        "in_standard_filter": 0,
        "insert_after": "customer_group",
        "is_system_generated": 1,
        "is_virtual": 0,
        "label": "Donor Reference",
        "length": 0,
        "link_filters": None,
        "mandatory_depends_on": None,
        "modified": "2025-07-27 21:55:32.986424",
        "module": "Verenigingen",
        "name": "Customer-custom_donor_reference",
        "no_copy": 0,
        "non_negative": 0,
        "options": "Donor",
        "permlevel": 0,
        "placeholder": None,
        "precision": "",
        "print_hide": 0,
        "print_hide_if_no_value": 0,
        "print_width": None,
        "read_only": 0,
        "read_only_depends_on": None,
        "report_hide": 0,
        "reqd": 0,
        "search_index": 0,
        "show_dashboard": 0,
        "sort_options": 0,
        "translatable": 0,
        "unique": 0,
        "width": None
    },
    {
        "allow_in_quick_entry": 0,
        "allow_on_submit": 0,
        "bold": 0,
        "collapsible": 1,
        "collapsible_depends_on": None,
        "columns": 0,
        "default": None,
        "depends_on": None,
        "description": None,
        "docstatus": 0,
        "doctype": "Custom Field",
        "dt": "Sales Invoice",
        "fetch_from": None,
        "fetch_if_empty": 0,
        "fieldname": "custom_donation_section",
        "fieldtype": "Section Break",
        "hidden": 0,
        "hide_border": 0,
        "hide_days": 0,
        "hide_seconds": 0,
        "ignore_user_permissions": 0,
        "ignore_xss_filter": 0,
        "in_global_search": 0,
        "in_list_view": 0,
        "in_preview": 0,
        "in_standard_filter": 0,
        "insert_after": "btw_reporting_category",
        "is_system_generated": 1,
        "is_virtual": 0,
        "label": "Donation Information",
        "length": 0,
        "link_filters": None,
        "mandatory_depends_on": None,
        "modified": "2025-07-27 21:55:32.985725",
        "module": "Verenigingen",
        "name": "Sales Invoice-custom_donation_section",
        "no_copy": 0,
        "non_negative": 0,
        "options": None,
        "permlevel": 0,
        "placeholder": None,
        "precision": "",
        "print_hide": 0,
        "print_hide_if_no_value": 0,
        "print_width": None,
        "read_only": 0,
        "read_only_depends_on": None,
        "report_hide": 0,
        "reqd": 0,
        "search_index": 0,
        "show_dashboard": 0,
        "sort_options": 0,
        "translatable": 0,
        "unique": 0,
        "width": None
    },
    {
        "allow_in_quick_entry": 0,
        "allow_on_submit": 0,
        "bold": 0,
        "collapsible": 0,
        "collapsible_depends_on": None,
        "columns": 0,
        "default": None,
        "depends_on": None,
        "description": "Original donation record that created this invoice",
        "docstatus": 0,
        "doctype": "Custom Field",
        "dt": "Sales Invoice",
        "fetch_from": None,
        "fetch_if_empty": 0,
        "fieldname": "custom_source_donation",
        "fieldtype": "Link",
        "hidden": 0,
        "hide_border": 0,
        "hide_days": 0,
        "hide_seconds": 0,
        "ignore_user_permissions": 0,
        "ignore_xss_filter": 0,
        "in_global_search": 0,
        "in_list_view": 0,
        "in_preview": 0,
        "in_standard_filter": 0,
        "insert_after": "custom_donation_section",
        "is_system_generated": 1,
        "is_virtual": 0,
        "label": "Source Donation",
        "length": 0,
        "link_filters": None,
        "mandatory_depends_on": None,
        "modified": "2025-07-27 21:55:32.984793",
        "module": "Verenigingen",
        "name": "Sales Invoice-custom_source_donation",
        "no_copy": 0,
        "non_negative": 0,
        "options": "Donation",
        "permlevel": 0,
        "placeholder": None,
        "precision": "",
        "print_hide": 0,
        "print_hide_if_no_value": 0,
        "print_width": None,
        "read_only": 0,
        "read_only_depends_on": None,
        "report_hide": 0,
        "reqd": 0,
        "search_index": 0,
        "show_dashboard": 0,
        "sort_options": 0,
        "translatable": 0,
        "unique": 0,
        "width": None
    },
    {
        "allow_in_quick_entry": 0,
        "allow_on_submit": 0,
        "bold": 0,
        "collapsible": 0,
        "collapsible_depends_on": None,
        "columns": 0,
        "default": None,
        "depends_on": None,
        "description": None,
        "docstatus": 0,
        "doctype": "Custom Field",
        "dt": "Sales Invoice",
        "fetch_from": None,
        "fetch_if_empty": 0,
        "fieldname": "custom_membership_dues_schedule",
        "fieldtype": "Link",
        "hidden": 0,
        "hide_border": 0,
        "hide_days": 0,
        "hide_seconds": 0,
        "ignore_user_permissions": 0,
        "ignore_xss_filter": 0,
        "in_global_search": 0,
        "in_list_view": 0,
        "in_preview": 0,
        "in_standard_filter": 0,
        "insert_after": "membership_dues_section",
        "is_system_generated": 1,
        "is_virtual": 0,
        "label": "Membership Dues Schedule",
        "length": 0,
        "link_filters": None,
        "mandatory_depends_on": None,
        "modified": "2025-07-27 21:55:32.984163",
        "module": "Verenigingen",
        "name": "Sales Invoice-custom_membership_dues_schedule",
        "no_copy": 0,
        "non_negative": 0,
        "options": "Membership Dues Schedule",
        "permlevel": 0,
        "placeholder": None,
        "precision": "",
        "print_hide": 0,
        "print_hide_if_no_value": 0,
        "print_width": None,
        "read_only": 0,
        "read_only_depends_on": None,
        "report_hide": 0,
        "reqd": 0,
        "search_index": 0,
        "show_dashboard": 0,
        "sort_options": 0,
        "translatable": 0,
        "unique": 0,
        "width": None
    },
    {
        "allow_in_quick_entry": 0,
        "allow_on_submit": 0,
        "bold": 0,
        "collapsible": 0,
        "collapsible_depends_on": None,
        "columns": 0,
        "default": None,
        "depends_on": None,
        "description": None,
        "docstatus": 0,
        "doctype": "Custom Field",
        "dt": "Sales Invoice",
        "fetch_from": None,
        "fetch_if_empty": 0,
        "fieldname": "custom_contribution_mode",
        "fieldtype": "Data",
        "hidden": 0,
        "hide_border": 0,
        "hide_days": 0,
        "hide_seconds": 0,
        "ignore_user_permissions": 0,
        "ignore_xss_filter": 0,
        "in_global_search": 0,
        "in_list_view": 0,
        "in_preview": 0,
        "in_standard_filter": 0,
        "insert_after": "dues_schedule_column_break",
        "is_system_generated": 1,
        "is_virtual": 0,
        "label": "Contribution Mode",
        "length": 0,
        "link_filters": None,
        "mandatory_depends_on": None,
        "modified": "2025-07-27 21:55:32.983596",
        "module": "Verenigingen",
        "name": "Sales Invoice-custom_contribution_mode",
        "no_copy": 0,
        "non_negative": 0,
        "options": None,
        "permlevel": 0,
        "placeholder": None,
        "precision": "",
        "print_hide": 0,
        "print_hide_if_no_value": 0,
        "print_width": None,
        "read_only": 1,
        "read_only_depends_on": None,
        "report_hide": 0,
        "reqd": 0,
        "search_index": 0,
        "show_dashboard": 0,
        "sort_options": 0,
        "translatable": 0,
        "unique": 0,
        "width": None
    },
    {
        "allow_in_quick_entry": 0,
        "allow_on_submit": 0,
        "bold": 0,
        "collapsible": 0,
        "collapsible_depends_on": None,
        "columns": 0,
        "default": None,
        "depends_on": None,
        "description": None,
        "docstatus": 0,
        "doctype": "Custom Field",
        "dt": "Sales Invoice",
        "fetch_from": None,
        "fetch_if_empty": 0,
        "fieldname": "custom_coverage_start_date",
        "fieldtype": "Date",
        "hidden": 0,
        "hide_border": 0,
        "hide_days": 0,
        "hide_seconds": 0,
        "ignore_user_permissions": 0,
        "ignore_xss_filter": 0,
        "in_global_search": 0,
        "in_list_view": 0,
        "in_preview": 0,
        "in_standard_filter": 0,
        "insert_after": "coverage_period_section",
        "is_system_generated": 1,
        "is_virtual": 0,
        "label": "Coverage Start Date",
        "length": 0,
        "link_filters": None,
        "mandatory_depends_on": None,
        "modified": "2025-07-27 21:55:32.981455",
        "module": "Verenigingen",
        "name": "Sales Invoice-custom_coverage_start_date",
        "no_copy": 0,
        "non_negative": 0,
        "options": None,
        "permlevel": 0,
        "placeholder": None,
        "precision": "",
        "print_hide": 0,
        "print_hide_if_no_value": 0,
        "print_width": None,
        "read_only": 0,
        "read_only_depends_on": None,
        "report_hide": 0,
        "reqd": 0,
        "search_index": 0,
        "show_dashboard": 0,
        "sort_options": 0,
        "translatable": 0,
        "unique": 0,
        "width": None
    },
    {
        "allow_in_quick_entry": 0,
        "allow_on_submit": 0,
        "bold": 0,
        "collapsible": 0,
        "collapsible_depends_on": None,
        "columns": 0,
        "default": None,
        "depends_on": None,
        "description": None,
        "docstatus": 0,
        "doctype": "Custom Field",
        "dt": "Sales Invoice",
        "fetch_from": None,
        "fetch_if_empty": 0,
        "fieldname": "custom_coverage_end_date",
        "fieldtype": "Date",
        "hidden": 0,
        "hide_border": 0,
        "hide_days": 0,
        "hide_seconds": 0,
        "ignore_user_permissions": 0,
        "ignore_xss_filter": 0,
        "in_global_search": 0,
        "in_list_view": 0,
        "in_preview": 0,
        "in_standard_filter": 0,
        "insert_after": "coverage_period_column_break",
        "is_system_generated": 1,
        "is_virtual": 0,
        "label": "Coverage End Date",
        "length": 0,
        "link_filters": None,
        "mandatory_depends_on": None,
        "modified": "2025-07-27 21:55:32.980765",
        "module": "Verenigingen",
        "name": "Sales Invoice-custom_coverage_end_date",
        "no_copy": 0,
        "non_negative": 0,
        "options": None,
        "permlevel": 0,
        "placeholder": None,
        "precision": "",
        "print_hide": 0,
        "print_hide_if_no_value": 0,
        "print_width": None,
        "read_only": 0,
        "read_only_depends_on": None,
        "report_hide": 0,
        "reqd": 0,
        "search_index": 0,
        "show_dashboard": 0,
        "sort_options": 0,
        "translatable": 0,
        "unique": 0,
        "width": None
    },
    {
        "allow_in_quick_entry": 0,
        "allow_on_submit": 0,
        "bold": 0,
        "collapsible": 0,
        "collapsible_depends_on": None,
        "columns": 0,
        "default": None,
        "depends_on": None,
        "description": "If this invoice is paid by someone other than the member (e.g., parent, spouse)",
        "docstatus": 0,
        "doctype": "Custom Field",
        "dt": "Sales Invoice",
        "fetch_from": None,
        "fetch_if_empty": 0,
        "fieldname": "custom_paying_for_member",
        "fieldtype": "Link",
        "hidden": 0,
        "hide_border": 0,
        "hide_days": 0,
        "hide_seconds": 0,
        "ignore_user_permissions": 0,
        "ignore_xss_filter": 0,
        "in_global_search": 0,
        "in_list_view": 0,
        "in_preview": 0,
        "in_standard_filter": 0,
        "insert_after": "partner_payment_section",
        "is_system_generated": 1,
        "is_virtual": 0,
        "label": "Paying for Member",
        "length": 0,
        "link_filters": None,
        "mandatory_depends_on": None,
        "modified": "2025-07-27 21:55:32.980133",
        "module": "Verenigingen",
        "name": "Sales Invoice-custom_paying_for_member",
        "no_copy": 0,
        "non_negative": 0,
        "options": "Member",
        "permlevel": 0,
        "placeholder": None,
        "precision": "",
        "print_hide": 0,
        "print_hide_if_no_value": 0,
        "print_width": None,
        "read_only": 0,
        "read_only_depends_on": None,
        "report_hide": 0,
        "reqd": 0,
        "search_index": 0,
        "show_dashboard": 0,
        "sort_options": 0,
        "translatable": 0,
        "unique": 0,
        "width": None
    },
    {
        "allow_in_quick_entry": 0,
        "allow_on_submit": 0,
        "bold": 0,
        "collapsible": 0,
        "collapsible_depends_on": None,
        "columns": 0,
        "default": None,
        "depends_on": "eval:doc.custom_paying_for_member",
        "description": None,
        "docstatus": 0,
        "doctype": "Custom Field",
        "dt": "Sales Invoice",
        "fetch_from": None,
        "fetch_if_empty": 0,
        "fieldname": "custom_payment_relationship",
        "fieldtype": "Select",
        "hidden": 0,
        "hide_border": 0,
        "hide_days": 0,
        "hide_seconds": 0,
        "ignore_user_permissions": 0,
        "ignore_xss_filter": 0,
        "in_global_search": 0,
        "in_list_view": 0,
        "in_preview": 0,
        "in_standard_filter": 0,
        "insert_after": "partner_payment_column_break",
        "is_system_generated": 1,
        "is_virtual": 0,
        "label": "Payment Relationship",
        "length": 0,
        "link_filters": None,
        "mandatory_depends_on": None,
        "modified": "2025-07-27 21:55:32.968661",
        "module": "Verenigingen",
        "name": "Sales Invoice-custom_payment_relationship",
        "no_copy": 0,
        "non_negative": 0,
        "options": "\nParent\nSpouse\nPartner\nGuardian\nOther Family Member\nOrganization\nOther",
        "permlevel": 0,
        "placeholder": None,
        "precision": "",
        "print_hide": 0,
        "print_hide_if_no_value": 0,
        "print_width": None,
        "read_only": 0,
        "read_only_depends_on": None,
        "report_hide": 0,
        "reqd": 0,
        "search_index": 0,
        "show_dashboard": 0,
        "sort_options": 0,
        "translatable": 0,
        "unique": 0,
        "width": None
    },
    {
        "allow_in_quick_entry": 0,
        "allow_on_submit": 0,
        "bold": 0,
        "collapsible": 0,
        "collapsible_depends_on": None,
        "columns": 0,
        "default": None,
        "depends_on": None,
        "description": "Direct link to the associated Member record",
        "docstatus": 0,
        "doctype": "Custom Field",
        "dt": "Customer",
        "fetch_from": None,
        "fetch_if_empty": 0,
        "fieldname": "member",
        "fieldtype": "Link",
        "hidden": 0,
        "hide_border": 0,
        "hide_days": 0,
        "hide_seconds": 0,
        "ignore_user_permissions": 0,
        "ignore_xss_filter": 0,
        "in_global_search": 1,
        "in_list_view": 1,
        "in_preview": 1,
        "in_standard_filter": 1,
        "insert_after": "customer_name",
        "is_system_generated": 0,
        "is_virtual": 0,
        "label": "Member",
        "length": 0,
        "link_filters": None,
        "mandatory_depends_on": None,
        "modified": "2025-01-20 12:00:00",
        "module": "Verenigingen",
        "name": "Customer-member",
        "no_copy": 0,
        "non_negative": 0,
        "options": "Member",
        "permlevel": 0,
        "placeholder": None,
        "precision": "",
        "print_hide": 0,
        "print_hide_if_no_value": 0,
        "print_width": None,
        "read_only": 0,
        "read_only_depends_on": None,
        "report_hide": 0,
        "reqd": 0,
        "search_index": 1,
        "show_dashboard": 1,
        "sort_options": 0,
        "translatable": 0,
        "unique": 1,
        "width": None
    },
    {
        "allow_in_quick_entry": 0,
        "allow_on_submit": 0,
        "bold": 0,
        "collapsible": 0,
        "collapsible_depends_on": None,
        "columns": 0,
        "default": None,
        "depends_on": None,
        "description": "Account number from E-Boekhouden system",
        "docstatus": 0,
        "doctype": "Custom Field",
        "dt": "Account",
        "fetch_from": None,
        "fetch_if_empty": 0,
        "fieldname": "eboekhouden_grootboek_nummer",
        "fieldtype": "Data",
        "hidden": 0,
        "hide_border": 0,
        "hide_days": 0,
        "hide_seconds": 0,
        "ignore_user_permissions": 0,
        "ignore_xss_filter": 0,
        "in_global_search": 0,
        "in_list_view": 0,
        "in_preview": 0,
        "in_standard_filter": 0,
        "insert_after": "account_number",
        "is_system_generated": 0,
        "is_virtual": 0,
        "label": "E-Boekhouden Account Number",
        "length": 0,
        "link_filters": None,
        "mandatory_depends_on": None,
        "modified": "2025-01-02 12:00:00",
        "module": "Verenigingen",
        "name": "Account-eboekhouden_grootboek_nummer",
        "no_copy": 0,
        "non_negative": 0,
        "options": None,
        "permlevel": 0,
        "placeholder": None,
        "precision": "",
        "print_hide": 0,
        "print_hide_if_no_value": 0,
        "print_width": None,
        "read_only": 0,
        "read_only_depends_on": None,
        "report_hide": 0,
        "reqd": 0,
        "search_index": 1,
        "show_dashboard": 0,
        "sort_options": 0,
        "translatable": 0,
        "unique": 0,
        "width": None
    }
]

# E-Boekhouden related fields (reassign module to "Verenigingen" for our management)
eboekhouden_fields = [
    {
        "allow_in_quick_entry": 0,
        "allow_on_submit": 0,
        "bold": 0,
        "collapsible": 0,
        "collapsible_depends_on": None,
        "columns": 0,
        "default": None,
        "depends_on": None,
        "description": "E-Boekhouden mutation number for tracking",
        "docstatus": 0,
        "doctype": "Custom Field",
        "dt": "Purchase Invoice",
        "fetch_from": None,
        "fetch_if_empty": 0,
        "fieldname": "eboekhouden_mutation_nr",
        "fieldtype": "Data",
        "hidden": 0,
        "hide_border": 0,
        "hide_days": 0,
        "hide_seconds": 0,
        "ignore_user_permissions": 0,
        "ignore_xss_filter": 0,
        "in_global_search": 0,
        "in_list_view": 0,
        "in_preview": 0,
        "in_standard_filter": 0,
        "insert_after": "cost_center",
        "is_system_generated": 1,
        "is_virtual": 0,
        "label": "E-Boekhouden Mutation Nr",
        "length": 0,
        "link_filters": None,
        "mandatory_depends_on": None,
        "modified": "2025-08-03 07:24:12.486588",
        "module": "Verenigingen",
        "name": "Purchase Invoice-eboekhouden_mutation_nr",
        "no_copy": 0,
        "non_negative": 0,
        "options": None,
        "permlevel": 0,
        "placeholder": None,
        "precision": "",
        "print_hide": 0,
        "print_hide_if_no_value": 0,
        "print_width": None,
        "read_only": 1,
        "read_only_depends_on": None,
        "report_hide": 0,
        "reqd": 0,
        "search_index": 0,
        "show_dashboard": 0,
        "sort_options": 0,
        "translatable": 0,
        "unique": 1,
        "width": None
    },
    {
        "allow_in_quick_entry": 0,
        "allow_on_submit": 0,
        "bold": 0,
        "collapsible": 0,
        "collapsible_depends_on": None,
        "columns": 0,
        "default": None,
        "depends_on": None,
        "description": "E-Boekhouden mutation number for tracking",
        "docstatus": 0,
        "doctype": "Custom Field",
        "dt": "Sales Invoice",
        "fetch_from": None,
        "fetch_if_empty": 0,
        "fieldname": "eboekhouden_mutation_nr",
        "fieldtype": "Data",
        "hidden": 0,
        "hide_border": 0,
        "hide_days": 0,
        "hide_seconds": 0,
        "ignore_user_permissions": 0,
        "ignore_xss_filter": 0,
        "in_global_search": 0,
        "in_list_view": 0,
        "in_preview": 0,
        "in_standard_filter": 0,
        "insert_after": "cost_center",
        "is_system_generated": 1,
        "is_virtual": 0,
        "label": "E-Boekhouden Mutation Nr",
        "length": 0,
        "link_filters": None,
        "mandatory_depends_on": None,
        "modified": "2025-08-03 07:24:03.180603",
        "module": "Verenigingen",
        "name": "Sales Invoice-eboekhouden_mutation_nr",
        "no_copy": 0,
        "non_negative": 0,
        "options": None,
        "permlevel": 0,
        "placeholder": None,
        "precision": "",
        "print_hide": 0,
        "print_hide_if_no_value": 0,
        "print_width": None,
        "read_only": 1,
        "read_only_depends_on": None,
        "report_hide": 0,
        "reqd": 0,
        "search_index": 0,
        "show_dashboard": 0,
        "sort_options": 0,
        "translatable": 0,
        "unique": 1,
        "width": None
    },
    {
        "allow_in_quick_entry": 0,
        "allow_on_submit": 1,
        "bold": 0,
        "collapsible": 0,
        "collapsible_depends_on": None,
        "columns": 0,
        "default": None,
        "depends_on": None,
        "description": "E-Boekhouden mutation number for tracking",
        "docstatus": 0,
        "doctype": "Custom Field",
        "dt": "Journal Entry",
        "fetch_from": None,
        "fetch_if_empty": 0,
        "fieldname": "eboekhouden_mutation_nr",
        "fieldtype": "Data",
        "hidden": 0,
        "hide_border": 0,
        "hide_days": 0,
        "hide_seconds": 0,
        "ignore_user_permissions": 0,
        "ignore_xss_filter": 0,
        "in_global_search": 0,
        "in_list_view": 0,
        "in_preview": 0,
        "in_standard_filter": 0,
        "insert_after": "naming_series",
        "is_system_generated": 1,
        "is_virtual": 0,
        "label": "E-Boekhouden Mutation Number",
        "length": 0,
        "link_filters": None,
        "mandatory_depends_on": None,
        "modified": "2025-08-01 20:29:01.930943",
        "module": "Verenigingen",
        "name": "Journal Entry-eboekhouden_mutation_nr",
        "no_copy": 0,
        "non_negative": 0,
        "options": None,
        "permlevel": 0,
        "placeholder": None,
        "precision": "",
        "print_hide": 0,
        "print_hide_if_no_value": 0,
        "print_width": None,
        "read_only": 1,
        "read_only_depends_on": None,
        "report_hide": 0,
        "reqd": 0,
        "search_index": 0,
        "show_dashboard": 0,
        "sort_options": 0,
        "translatable": 0,
        "unique": 1,
        "width": None
    },
    {
        "allow_in_quick_entry": 0,
        "allow_on_submit": 0,
        "bold": 0,
        "collapsible": 0,
        "collapsible_depends_on": None,
        "columns": 0,
        "default": None,
        "depends_on": None,
        "description": None,
        "docstatus": 0,
        "doctype": "Custom Field",
        "dt": "Supplier",
        "fetch_from": None,
        "fetch_if_empty": 0,
        "fieldname": "eboekhouden_relation_code",
        "fieldtype": "Data",
        "hidden": 0,
        "hide_border": 0,
        "hide_days": 0,
        "hide_seconds": 0,
        "ignore_user_permissions": 0,
        "ignore_xss_filter": 0,
        "in_global_search": 0,
        "in_list_view": 0,
        "in_preview": 0,
        "in_standard_filter": 0,
        "insert_after": "supplier_name",
        "is_system_generated": 1,
        "is_virtual": 0,
        "label": "E-Boekhouden Relation Code",
        "length": 0,
        "link_filters": None,
        "mandatory_depends_on": None,
        "modified": "2025-08-01 20:29:01.913129",
        "module": "Verenigingen",
        "name": "Supplier-eboekhouden_relation_code",
        "no_copy": 0,
        "non_negative": 0,
        "options": None,
        "permlevel": 0,
        "placeholder": None,
        "precision": "",
        "print_hide": 0,
        "print_hide_if_no_value": 0,
        "print_width": None,
        "read_only": 0,
        "read_only_depends_on": None,
        "report_hide": 0,
        "reqd": 0,
        "search_index": 0,
        "show_dashboard": 0,
        "sort_options": 0,
        "translatable": 0,
        "unique": 1,
        "width": None
    },
    {
        "allow_in_quick_entry": 0,
        "allow_on_submit": 0,
        "bold": 0,
        "collapsible": 0,
        "collapsible_depends_on": None,
        "columns": 0,
        "default": None,
        "depends_on": None,
        "description": None,
        "docstatus": 0,
        "doctype": "Custom Field",
        "dt": "Customer",
        "fetch_from": None,
        "fetch_if_empty": 0,
        "fieldname": "eboekhouden_relation_code",
        "fieldtype": "Data",
        "hidden": 0,
        "hide_border": 0,
        "hide_days": 0,
        "hide_seconds": 0,
        "ignore_user_permissions": 0,
        "ignore_xss_filter": 0,
        "in_global_search": 0,
        "in_list_view": 0,
        "in_preview": 0,
        "in_standard_filter": 0,
        "insert_after": "customer_name",
        "is_system_generated": 1,
        "is_virtual": 0,
        "label": "E-Boekhouden Relation Code",
        "length": 0,
        "link_filters": None,
        "mandatory_depends_on": None,
        "modified": "2025-08-01 20:29:01.907481",
        "module": "Verenigingen",
        "name": "Customer-eboekhouden_relation_code",
        "no_copy": 0,
        "non_negative": 0,
        "options": None,
        "permlevel": 0,
        "placeholder": None,
        "precision": "",
        "print_hide": 0,
        "print_hide_if_no_value": 0,
        "print_width": None,
        "read_only": 0,
        "read_only_depends_on": None,
        "report_hide": 0,
        "reqd": 0,
        "search_index": 0,
        "show_dashboard": 0,
        "sort_options": 0,
        "translatable": 0,
        "unique": 1,
        "width": None
    }
]

def main():
    """Generate complete custom field fixture"""
    
    # Combine all fields
    all_fields = verenigingen_fields + eboekhouden_fields
    
    # Write to fixture file
    fixture_path = Path("/home/frappe/frappe-bench/apps/verenigingen/verenigingen/fixtures/custom_field.json")
    
    with open(fixture_path, 'w', encoding='utf-8') as f:
        json.dump(all_fields, f, indent=1, ensure_ascii=False)
    
    print(f"✅ Exported {len(all_fields)} custom fields to {fixture_path}")
    print(f"   - Verenigingen module fields: {len(verenigingen_fields)}")  
    print(f"   - E-Boekhouden related fields: {len(eboekhouden_fields)}")
    
    return 0

if __name__ == "__main__":
    exit(main())