"""
Integration Tests for CSV Import with Enhanced Test Factory

Tests complete CSV import workflow using realistic Dutch association data
generated by EnhancedTestCase fixtures.
"""

import csv
import os
import tempfile

import frappe
from frappe.tests.utils import FrappeTestCase

from verenigingen.tests.fixtures.enhanced_test_factory import EnhancedTestCase
from verenigingen.utils.csv.secure_csv_parser import SecureCSVParser


class TestCSVImportIntegration(EnhancedTestCase):
	"""Integration tests for CSV import with realistic test data"""

	def setUp(self):
		"""Set up test environment with realistic data"""
		super().setUp()
		self.parser = SecureCSVParser()
		self.temp_files = []

	def tearDown(self):
		"""Clean up temporary CSV files"""
		for temp_file in self.temp_files:
			if os.path.exists(temp_file):
				try:
					os.unlink(temp_file)
				except OSError:
					pass
		super().tearDown()

	def _create_temp_csv(self, data, suffix='.csv'):
		"""Create temporary CSV file with test data"""
		temp_file = tempfile.NamedTemporaryFile(
			mode='w',
			suffix=suffix,
			delete=False,
			encoding='utf-8'
		)

		if data:
			writer = csv.DictWriter(temp_file, fieldnames=data[0].keys())
			writer.writeheader()
			writer.writerows(data)

		temp_file.close()
		self.temp_files.append(temp_file.name)
		return temp_file.name

	def test_import_dutch_members_with_tussenvoegsel(self):
		"""Test importing Dutch members with name particles (tussenvoegsel)"""
		csv_data = [
			{
				"first_name": "Jan",
				"tussenvoegsel": "van",
				"last_name": "Dijk",
				"email": "jan.van.dijk@example.com",
				"birth_date": "1985-05-15",
				"postal_code": "1012 AB",
				"city": "Amsterdam"
			},
			{
				"first_name": "Maria",
				"tussenvoegsel": "de",
				"last_name": "Jong",
				"email": "maria.de.jong@example.com",
				"birth_date": "1990-08-22",
				"postal_code": "3011 CD",
				"city": "Rotterdam"
			}
		]

		temp_file = self._create_temp_csv(csv_data)
		result = self.parser._read_file_from_path(temp_file)

		self.assertEqual(len(result), 2)
		self.assertEqual(result[0]["first_name"], "Jan")
		self.assertEqual(result[0]["tussenvoegsel"], "van")
		self.assertEqual(result[0]["last_name"], "Dijk")
		self.assertEqual(result[1]["tussenvoegsel"], "de")

	def test_import_dutch_postal_codes(self):
		"""Test importing various Dutch postal code formats"""
		csv_data = [
			{"postal_code": "1234 AB", "city": "Amsterdam"},
			{"postal_code": "5678CD", "city": "Utrecht"},  # No space
			{"postal_code": "9012 EF", "city": "Groningen"},
		]

		temp_file = self._create_temp_csv(csv_data)
		result = self.parser._read_file_from_path(temp_file)

		self.assertEqual(len(result), 3)
		# Parser doesn't validate format, just reads - validation happens in data_transformers
		self.assertEqual(result[0]["postal_code"], "1234 AB")
		self.assertEqual(result[1]["postal_code"], "5678CD")

	def test_import_dutch_phone_numbers(self):
		"""Test importing various Dutch phone number formats"""
		csv_data = [
			{"name": "Member 1", "phone": "+31 6 12345678"},  # International mobile
			{"name": "Member 2", "phone": "06-1234-5678"},    # National mobile with dashes
			{"name": "Member 3", "phone": "+31 20 1234567"},  # International landline
			{"name": "Member 4", "phone": "020-123-4567"},    # National landline
		]

		temp_file = self._create_temp_csv(csv_data)
		result = self.parser._read_file_from_path(temp_file)

		self.assertEqual(len(result), 4)
		self.assertEqual(result[0]["phone"], "+31 6 12345678")
		self.assertEqual(result[1]["phone"], "06-1234-5678")

	def test_import_dutch_iban_numbers(self):
		"""Test importing Dutch IBAN numbers with spaces"""
		csv_data = [
			{"name": "Member 1", "iban": "NL91 ABNA 0417 1643 00"},
			{"name": "Member 2", "iban": "NL02RABO0123456789"},
			{"name": "Member 3", "iban": "BE68 5390 0754 7034"},  # Belgian
		]

		temp_file = self._create_temp_csv(csv_data)
		result = self.parser._read_file_from_path(temp_file)

		self.assertEqual(len(result), 3)
		# Parser reads as-is, data_transformers will clean spaces
		self.assertIn("ABNA", result[0]["iban"])
		self.assertIn("RABO", result[1]["iban"])

	def test_import_membership_types_dutch_terms(self):
		"""Test importing Dutch membership status terms"""
		csv_data = [
			{"name": "Active Member", "status": "lid"},
			{"name": "Deceased Member", "status": "overleden"},
			{"name": "Cancelled Member", "status": "opgezegd"},
			{"name": "Expelled Member", "status": "geroyeerd"},
		]

		temp_file = self._create_temp_csv(csv_data)
		result = self.parser._read_file_from_path(temp_file)

		self.assertEqual(len(result), 4)
		self.assertEqual(result[0]["status"], "lid")
		self.assertEqual(result[1]["status"], "overleden")
		self.assertEqual(result[2]["status"], "opgezegd")

	def test_import_dates_multiple_formats(self):
		"""Test importing dates in various common formats"""
		csv_data = [
			{"name": "Member 1", "birth_date": "1990-05-15"},      # ISO format
			{"name": "Member 2", "birth_date": "15-05-1990"},      # Dutch DD-MM-YYYY
			{"name": "Member 3", "birth_date": "15/05/1990"},      # Dutch with slashes
			{"name": "Member 4", "birth_date": "05/15/1990"},      # US MM/DD/YYYY
		]

		temp_file = self._create_temp_csv(csv_data)
		result = self.parser._read_file_from_path(temp_file)

		self.assertEqual(len(result), 4)
		# Parser reads as strings, date parsing happens in data_transformers
		self.assertEqual(result[0]["birth_date"], "1990-05-15")
		self.assertEqual(result[1]["birth_date"], "15-05-1990")

	def test_import_with_empty_and_null_values(self):
		"""Test importing CSV with various empty/null indicators"""
		csv_data = [
			{"name": "Member 1", "email": "test@example.com", "phone": "-"},
			{"name": "Member 2", "email": "-", "phone": "0612345678"},
			{"name": "Member 3", "email": "N/A", "phone": "NB"},
		]

		temp_file = self._create_temp_csv(csv_data)
		result = self.parser._read_file_from_path(temp_file)

		self.assertEqual(len(result), 3)
		# Parser cleans "-" and "NB" to None (per parse_csv_content logic)
		self.assertIsNone(result[0]["phone"])
		self.assertIsNone(result[1]["email"])
		# N/A is NOT cleaned by parser - that happens in data_transformers.clean_value()
		self.assertEqual(result[2]["email"], "N/A")
		self.assertIsNone(result[2]["phone"])

	def test_import_semicolon_delimited_dutch_csv(self):
		"""Test importing CSV with semicolon delimiter (common in Dutch Excel exports)"""
		csv_content = """name;email;phone
Jan van Dijk;jan@example.com;0612345678
Maria de Jong;maria@example.com;0687654321
"""

		temp_file = tempfile.NamedTemporaryFile(
			mode='w',
			suffix='.csv',
			delete=False,
			encoding='utf-8'
		)
		temp_file.write(csv_content)
		temp_file.close()
		self.temp_files.append(temp_file.name)

		result = self.parser._read_file_from_path(temp_file.name)

		self.assertEqual(len(result), 2)
		self.assertEqual(result[0]["name"], "Jan van Dijk")
		self.assertEqual(result[1]["name"], "Maria de Jong")

	def test_import_utf8_with_bom(self):
		"""Test importing UTF-8 CSV with BOM (common from Windows Excel)"""
		# Don't include BOM in the content string - utf-8-sig encoding handles it
		csv_content = "name,city\nJohán,Arnhem\nMariël,Utrecht\n"

		temp_file = tempfile.NamedTemporaryFile(
			mode='w',
			suffix='.csv',
			delete=False,
			encoding='utf-8-sig'
		)
		temp_file.write(csv_content)
		temp_file.close()
		self.temp_files.append(temp_file.name)

		result = self.parser._read_file_from_path(temp_file.name)

		self.assertEqual(len(result), 2)
		# BOM should be stripped by utf-8-sig encoding (tried first in encoding list)
		self.assertIn("name", result[0])
		self.assertEqual(result[0]["name"], "Johán")

	def test_import_dutch_currency_values(self):
		"""Test importing Dutch currency values with euro symbols"""
		csv_data = [
			{"name": "Member 1", "dues": "€ 25,00"},
			{"name": "Member 2", "dues": "25.00"},
			{"name": "Member 3", "dues": "€25,50"},
		]

		temp_file = self._create_temp_csv(csv_data)
		result = self.parser._read_file_from_path(temp_file)

		self.assertEqual(len(result), 3)
		# Parser reads as strings, currency cleaning happens in data_transformers
		self.assertIn("25", result[0]["dues"])
		self.assertEqual(result[1]["dues"], "25.00")

	def test_import_filters_completely_empty_rows(self):
		"""Test that parser filters out completely empty rows"""
		csv_content = """name,email,phone
Jan van Dijk,jan@example.com,0612345678
,,
,,-
Maria de Jong,maria@example.com,0687654321
"""

		temp_file = tempfile.NamedTemporaryFile(
			mode='w',
			suffix='.csv',
			delete=False,
			encoding='utf-8'
		)
		temp_file.write(csv_content)
		temp_file.close()
		self.temp_files.append(temp_file.name)

		result = self.parser._read_file_from_path(temp_file.name)

		# Should only have 2 data rows (empty rows filtered)
		self.assertEqual(len(result), 2)
		self.assertEqual(result[0]["name"], "Jan van Dijk")
		self.assertEqual(result[1]["name"], "Maria de Jong")

	def test_import_csv_injection_prevention(self):
		"""Test that CSV injection attempts are properly handled"""
		csv_data = [
			{"name": "Normal User", "email": "normal@example.com"},
			{"name": "=1+1", "email": "suspicious@example.com"},  # Formula injection
		]

		temp_file = self._create_temp_csv(csv_data)
		result = self.parser._read_file_from_path(temp_file)

		# Parser reads data as-is, security validation happens in data_transformers
		self.assertEqual(len(result), 2)
		self.assertEqual(result[1]["name"], "=1+1")  # Read as string, not executed

	def test_import_large_csv_file(self):
		"""Test importing larger CSV file (performance test)"""
		# Create CSV with 100 realistic member records
		csv_data = []
		for i in range(100):
			csv_data.append({
				"first_name": f"Member{i}",
				"last_name": "Test",
				"email": f"member{i}@example.com",
				"birth_date": "1990-01-01",
				"postal_code": "1234 AB",
				"city": "Amsterdam"
			})

		temp_file = self._create_temp_csv(csv_data)
		result = self.parser._read_file_from_path(temp_file)

		self.assertEqual(len(result), 100)
		self.assertEqual(result[0]["first_name"], "Member0")
		self.assertEqual(result[99]["first_name"], "Member99")

	def test_import_with_special_dutch_characters(self):
		"""Test importing names with special Dutch characters"""
		csv_data = [
			{"name": "François", "city": "Haarlem"},
			{"name": "Zoë", "city": "Nijmegen"},
			{"name": "Sören", "city": "Arnhem"},
		]

		temp_file = self._create_temp_csv(csv_data)
		result = self.parser._read_file_from_path(temp_file)

		self.assertEqual(len(result), 3)
		self.assertEqual(result[0]["name"], "François")
		self.assertEqual(result[1]["name"], "Zoë")
		self.assertEqual(result[2]["name"], "Sören")

	def test_import_country_codes(self):
		"""Test importing country codes"""
		csv_data = [
			{"name": "Dutch Member", "country": "NL"},
			{"name": "Belgian Member", "country": "BE"},
			{"name": "German Member", "country": "DE"},
		]

		temp_file = self._create_temp_csv(csv_data)
		result = self.parser._read_file_from_path(temp_file)

		self.assertEqual(len(result), 3)
		self.assertEqual(result[0]["country"], "NL")
		self.assertEqual(result[1]["country"], "BE")
		# Country code conversion happens in data_transformers
